In [1]:
import pandas as pd 
import datetime as dt
import numpy as np 

otu_file = "DataSets/belly_button_biodiversity_otu_id.csv"
sample_meta_file = "DataSets/Belly_Button_Biodiversity_Metadata.csv"
samples_file = "DataSets/belly_button_biodiversity_samples.csv"
columns_file = "DataSets/metadata_columns.csv"

otu_df = pd.read_csv(otu_file)
meta_df = pd.read_csv(sample_meta_file)
sample_df = pd.read_csv(samples_file)
column_df = pd.read_csv(columns_file)

In [25]:
#otu_df.head()

otu_desc = {}

for o in range(0, len(otu_df["otu_id"])):
    oid = otu_df["otu_id"][o]
    ltf = otu_df["lowest_taxonomic_unit_found"][o]
               
    otu_desc[oid] = ltf
    
otu_desc

{1: 'Archaea;Euryarchaeota;Halobacteria;Halobacteriales;Halobacteriaceae;Halococcus',
 2: 'Archaea;Euryarchaeota;Halobacteria;Halobacteriales;Halobacteriaceae;Halococcus',
 3: 'Archaea;Euryarchaeota;Halobacteria;Halobacteriales;Halobacteriaceae;Natronorubrum',
 4: 'Archaea;Euryarchaeota;Methanobacteria;Methanobacteriales;Methanobacteriaceae;Methanobrevibacter',
 5: 'Archaea;Euryarchaeota;Methanobacteria;Methanobacteriales;Methanobacteriaceae;Methanobrevibacter',
 6: 'Archaea;Euryarchaeota;Methanobacteria;Methanobacteriales;Methanobacteriaceae;Methanobrevibacter',
 7: 'Bacteria',
 8: 'Bacteria',
 9: 'Bacteria',
 10: 'Bacteria',
 11: 'Bacteria',
 12: 'Bacteria',
 13: 'Bacteria',
 14: 'Bacteria',
 15: 'Bacteria',
 16: 'Bacteria',
 17: 'Bacteria',
 18: 'Bacteria',
 19: 'Bacteria',
 20: 'Bacteria',
 21: 'Bacteria',
 22: 'Bacteria',
 23: 'Bacteria',
 24: 'Bacteria',
 25: 'Bacteria',
 26: 'Bacteria',
 27: 'Bacteria',
 28: 'Bacteria',
 29: 'Bacteria',
 30: 'Bacteria',
 31: 'Bacteria',
 32: 'Bacteria',
 33: 'Bacteria',
 34: 'Bacteria',
 35: 'Bacteria',
 36: 'Bacteria',
 37: 'Bacteria',
 38: 'Bacteria',
 39: 'Bacteria',
 40: 'Bacteria',
 41: 'Bacteria',
 42: 'Bacteria',
 43: 'Bacteria',
 44: 'Bacteria',
 45: 'Bacteria',
 46: 'Bacteria',
 47: 'Bacteria',
 48: 'Bacteria',
 49: 'Bacteria',
 50: 'Bacteria',
 51: 'Bacteria',
 52: 'Bacteria',
 53: 'Bacteria',
 54: 'Bacteria',
 55: 'Bacteria',
 56: 'Bacteria',
 57: 'Bacteria',
 58: 'Bacteria',
 59: 'Bacteria',
 60: 'Bacteria',
 61: 'Bacteria',
 62: 'Bacteria',
 63: 'Bacteria',
 64: 'Bacteria',
 65: 'Bacteria',
 66: 'Bacteria',
 67: 'Bacteria',
 68: 'Bacteria',
 69: 'Bacteria',
 70: 'Bacteria',
 71: 'Bacteria',
 72: 'Bacteria',
 73: 'Bacteria',
 74: 'Bacteria',
 75: 'Bacteria',
 76: 'Bacteria',
 77: 'Bacteria',
 78: 'Bacteria',
 79: 'Bacteria',
 80: 'Bacteria',
 81: 'Bacteria',
 82: 'Bacteria',
 83: 'Bacteria',
 84: 'Bacteria',
 85: 'Bacteria',
 86: 'Bacteria',
 87: 'Bacteria',
 88: 'Bacteria',
 89: 'Bacteria',
 90: 'Bacteria',
 91: 'Bacteria',
 92: 'Bacteria',
 93: 'Bacteria',
 94: 'Bacteria',
 95: 'Bacteria',
 96: 'Bacteria',
 97: 'Bacteria',
 98: 'Bacteria',
 99: 'Bacteria',
 100: 'Bacteria',
 101: 'Bacteria',
 102: 'Bacteria',
 103: 'Bacteria',
 104: 'Bacteria',
 105: 'Bacteria',
 106: 'Bacteria',
 107: 'Bacteria',
 108: 'Bacteria',
 109: 'Bacteria',
 110: 'Bacteria',
 111: 'Bacteria',
 112: 'Bacteria',
 113: 'Bacteria',
 114: 'Bacteria',
 115: 'Bacteria',
 116: 'Bacteria',
 117: 'Bacteria',
 118: 'Bacteria',
 119: 'Bacteria',
 120: 'Bacteria',
 121: 'Bacteria',
 122: 'Bacteria',
 123: 'Bacteria',
 124: 'Bacteria',
 125: 'Bacteria',
 126: 'Bacteria',
 127: 'Bacteria',
 128: 'Bacteria',
 129: 'Bacteria',
 130: 'Bacteria',
 131: 'Bacteria',
 132: 'Bacteria',
 133: 'Bacteria',
 134: 'Bacteria',
 135: 'Bacteria',
 136: 'Bacteria',
 137: 'Bacteria',
 138: 'Bacteria',
 139: 'Bacteria',
 140: 'Bacteria',
 141: 'Bacteria',
 142: 'Bacteria',
 143: 'Bacteria',
 144: 'Bacteria',
 145: 'Bacteria',
 146: 'Bacteria',
 147: 'Bacteria',
 148: 'Bacteria',
 149: 'Bacteria',
 150: 'Bacteria',
 151: 'Bacteria',
 152: 'Bacteria',
 153: 'Bacteria',
 154: 'Bacteria',
 155: 'Bacteria',
 156: 'Bacteria',
 157: 'Bacteria',
 158: 'Bacteria',
 159: 'Bacteria',
 160: 'Bacteria',
 161: 'Bacteria',
 162: 'Bacteria',
 163: 'Bacteria',
 164: 'Bacteria',
 165: 'Bacteria',
 166: 'Bacteria',
 167: 'Bacteria',
 168: 'Bacteria',
 169: 'Bacteria',
 170: 'Bacteria',
 171: 'Bacteria',
 172: 'Bacteria',
 173: 'Bacteria',
 174: 'Bacteria',
 175: 'Bacteria',
 176: 'Bacteria',
 177: 'Bacteria',
 178: 'Bacteria',
 179: 'Bacteria',
 180: 'Bacteria',
 181: 'Bacteria',
 182: 'Bacteria',
 183: 'Bacteria',
 184: 'Bacteria',
 185: 'Bacteria',
 186: 'Bacteria',
 187: 'Bacteria',
 188: 'Bacteria',
 189: 'Bacteria',
 190: 'Bacteria',
 191: 'Bacteria',
 192: 'Bacteria',
 193: 'Bacteria',
 194: 'Bacteria',
 195: 'Bacteria',
 196: 'Bacteria',
 197: 'Bacteria',
 198: 'Bacteria',
 199: 'Bacteria',
 200: 'Bacteria',
 201: 'Bacteria',
 202: 'Bacteria',
 203: 'Bacteria',
 204: 'Bacteria',
 205: 'Bacteria',
 206: 'Bacteria',
 207: 'Bacteria',
 208: 'Bacteria',
 209: 'Bacteria',
 210: 'Bacteria',
 211: 'Bacteria',
 212: 'Bacteria',
 213: 'Bacteria',
 214: 'Bacteria',
 215: 'Bacteria',
 216: 'Bacteria',
 217: 'Bacteria',
 218: 'Bacteria',
 219: 'Bacteria',
 220: 'Bacteria',
 221: 'Bacteria',
 222: 'Bacteria',
 223: 'Bacteria',
 224: 'Bacteria',
 225: 'Bacteria',
 226: 'Bacteria',
 227: 'Bacteria',
 228: 'Bacteria',
 229: 'Bacteria',
 230: 'Bacteria',
 231: 'Bacteria',
 232: 'Bacteria',
 233: 'Bacteria',
 234: 'Bacteria',
 235: 'Bacteria',
 236: 'Bacteria',
 237: 'Bacteria',
 238: 'Bacteria',
 239: 'Bacteria',
 240: 'Bacteria',
 241: 'Bacteria',
 242: 'Bacteria',
 243: 'Bacteria',
 244: 'Bacteria',
 245: 'Bacteria',
 246: 'Bacteria',
 247: 'Bacteria',
 248: 'Bacteria',
 249: 'Bacteria',
 250: 'Bacteria',
 251: 'Bacteria',
 252: 'Bacteria',
 253: 'Bacteria',
 254: 'Bacteria',
 255: 'Bacteria',
 256: 'Bacteria',
 257: 'Bacteria',
 258: 'Bacteria',
 259: 'Bacteria',
 260: 'Bacteria',
 261: 'Bacteria',
 262: 'Bacteria',
 263: 'Bacteria',
 264: 'Bacteria',
 265: 'Bacteria',
 266: 'Bacteria',
 267: 'Bacteria',
 268: 'Bacteria',
 269: 'Bacteria',
 270: 'Bacteria',
 271: 'Bacteria',
 272: 'Bacteria',
 273: 'Bacteria',
 274: 'Bacteria',
 275: 'Bacteria',
 276: 'Bacteria',
 277: 'Bacteria',
 278: 'Bacteria',
 279: 'Bacteria',
 280: 'Bacteria',
 281: 'Bacteria',
 282: 'Bacteria',
 283: 'Bacteria',
 284: 'Bacteria',
 285: 'Bacteria',
 286: 'Bacteria',
 287: 'Bacteria',
 288: 'Bacteria',
 289: 'Bacteria',
 290: 'Bacteria',
 291: 'Bacteria',
 292: 'Bacteria',
 293: 'Bacteria',
 294: 'Bacteria',
 295: 'Bacteria',
 296: 'Bacteria',
 297: 'Bacteria',
 298: 'Bacteria',
 299: 'Bacteria',
 300: 'Bacteria',
 301: 'Bacteria',
 302: 'Bacteria',
 303: 'Bacteria',
 304: 'Bacteria',
 305: 'Bacteria',
 306: 'Bacteria',
 307: 'Bacteria',
 308: 'Bacteria',
 309: 'Bacteria',
 310: 'Bacteria',
 311: 'Bacteria',
 312: 'Bacteria',
 313: 'Bacteria',
 314: 'Bacteria',
 315: 'Bacteria',
 316: 'Bacteria',
 317: 'Bacteria',
 318: 'Bacteria',
 319: 'Bacteria',
 320: 'Bacteria',
 321: 'Bacteria',
 322: 'Bacteria',
 323: 'Bacteria',
 324: 'Bacteria',
 325: 'Bacteria',
 326: 'Bacteria',
 327: 'Bacteria',
 328: 'Bacteria',
 329: 'Bacteria',
 330: 'Bacteria',
 331: 'Bacteria',
 332: 'Bacteria',
 333: 'Bacteria',
 334: 'Bacteria',
 335: 'Bacteria',
 336: 'Bacteria',
 337: 'Bacteria',
 338: 'Bacteria',
 339: 'Bacteria',
 340: 'Bacteria',
 341: 'Bacteria',
 342: 'Bacteria',
 343: 'Bacteria',
 344: 'Bacteria',
 345: 'Bacteria',
 346: 'Bacteria',
 347: 'Bacteria',
 348: 'Bacteria',
 349: 'Bacteria',
 350: 'Bacteria',
 351: 'Bacteria',
 352: 'Bacteria',
 353: 'Bacteria',
 354: 'Bacteria',
 355: 'Bacteria',
 356: 'Bacteria',
 357: 'Bacteria',
 358: 'Bacteria',
 359: 'Bacteria',
 360: 'Bacteria',
 361: 'Bacteria',
 362: 'Bacteria',
 363: 'Bacteria',
 364: 'Bacteria',
 365: 'Bacteria',
 366: 'Bacteria',
 367: 'Bacteria',
 368: 'Bacteria',
 369: 'Bacteria',
 370: 'Bacteria',
 371: 'Bacteria',
 372: 'Bacteria',
 373: 'Bacteria',
 374: 'Bacteria',
 375: 'Bacteria',
 376: 'Bacteria',
 377: 'Bacteria',
 378: 'Bacteria',
 379: 'Bacteria',
 380: 'Bacteria',
 381: 'Bacteria',
 382: 'Bacteria',
 383: 'Bacteria',
 384: 'Bacteria',
 385: 'Bacteria',
 386: 'Bacteria',
 387: 'Bacteria',
 388: 'Bacteria',
 389: 'Bacteria',
 390: 'Bacteria',
 391: 'Bacteria',
 392: 'Bacteria',
 393: 'Bacteria',
 394: 'Bacteria',
 395: 'Bacteria',
 396: 'Bacteria',
 397: 'Bacteria',
 398: 'Bacteria',
 399: 'Bacteria',
 400: 'Bacteria',
 401: 'Bacteria',
 402: 'Bacteria',
 403: 'Bacteria',
 404: 'Bacteria',
 405: 'Bacteria',
 406: 'Bacteria',
 407: 'Bacteria',
 408: 'Bacteria',
 409: 'Bacteria',
 410: 'Bacteria',
 411: 'Bacteria',
 412: 'Bacteria',
 413: 'Bacteria',
 414: 'Bacteria',
 415: 'Bacteria',
 416: 'Bacteria',
 417: 'Bacteria',
 418: 'Bacteria',
 419: 'Bacteria',
 420: 'Bacteria',
 421: 'Bacteria',
 422: 'Bacteria',
 423: 'Bacteria',
 424: 'Bacteria',
 425: 'Bacteria',
 426: 'Bacteria',
 427: 'Bacteria',
 428: 'Bacteria',
 429: 'Bacteria',
 430: 'Bacteria',
 431: 'Bacteria',
 432: 'Bacteria',
 433: 'Bacteria',
 434: 'Bacteria',
 435: 'Bacteria',
 436: 'Bacteria',
 437: 'Bacteria',
 438: 'Bacteria',
 439: 'Bacteria',
 440: 'Bacteria',
 441: 'Bacteria',
 442: 'Bacteria',
 443: 'Bacteria',
 444: 'Bacteria',
 445: 'Bacteria',
 446: 'Bacteria',
 447: 'Bacteria',
 448: 'Bacteria',
 449: 'Bacteria',
 450: 'Bacteria',
 451: 'Bacteria',
 452: 'Bacteria',
 453: 'Bacteria',
 454: 'Bacteria',
 455: 'Bacteria',
 456: 'Bacteria',
 457: 'Bacteria',
 458: 'Bacteria',
 459: 'Bacteria',
 460: 'Bacteria',
 461: 'Bacteria',
 462: 'Bacteria',
 463: 'Bacteria',
 464: 'Bacteria',
 465: 'Bacteria',
 466: 'Bacteria',
 467: 'Bacteria',
 468: 'Bacteria',
 469: 'Bacteria',
 470: 'Bacteria',
 471: 'Bacteria',
 472: 'Bacteria',
 473: 'Bacteria',
 474: 'Bacteria',
 475: 'Bacteria',
 476: 'Bacteria',
 477: 'Bacteria',
 478: 'Bacteria',
 479: 'Bacteria',
 480: 'Bacteria',
 481: 'Bacteria',
 482: 'Bacteria',
 483: 'Bacteria',
 484: 'Bacteria',
 485: 'Bacteria',
 486: 'Bacteria',
 487: 'Bacteria',
 488: 'Bacteria',
 489: 'Bacteria',
 490: 'Bacteria',
 491: 'Bacteria',
 492: 'Bacteria',
 493: 'Bacteria',
 494: 'Bacteria',
 495: 'Bacteria',
 496: 'Bacteria',
 497: 'Bacteria',
 498: 'Bacteria',
 499: 'Bacteria',
 500: 'Bacteria',
 501: 'Bacteria',
 502: 'Bacteria',
 503: 'Bacteria',
 504: 'Bacteria',
 505: 'Bacteria',
 506: 'Bacteria',
 507: 'Bacteria',
 508: 'Bacteria',
 509: 'Bacteria',
 510: 'Bacteria',
 511: 'Bacteria',
 512: 'Bacteria',
 513: 'Bacteria',
 514: 'Bacteria',
 515: 'Bacteria',
 516: 'Bacteria',
 517: 'Bacteria',
 518: 'Bacteria',
 519: 'Bacteria',
 520: 'Bacteria;Acidobacteria;Acidobacteria_Gp1;Gp1',
 521: 'Bacteria;Acidobacteria;Acidobacteria_Gp1;Gp1',
 522: 'Bacteria;Acidobacteria;Acidobacteria_Gp1;Gp1',
 523: 'Bacteria;Acidobacteria;Acidobacteria_Gp1;Gp1',
 524: 'Bacteria;Acidobacteria;Acidobacteria_Gp1;Gp1',
 525: 'Bacteria;Acidobacteria;Acidobacteria_Gp10;Gp10',
 526: 'Bacteria;Acidobacteria;Acidobacteria_Gp16;Gp16',
 527: 'Bacteria;Acidobacteria;Acidobacteria_Gp16;Gp16',
 528: 'Bacteria;Acidobacteria;Acidobacteria_Gp16;Gp16',
 529: 'Bacteria;Acidobacteria;Acidobacteria_Gp2;Gp2',
 530: 'Bacteria;Acidobacteria;Acidobacteria_Gp2;Gp2',
 531: 'Bacteria;Acidobacteria;Acidobacteria_Gp2;Gp2',
 532: 'Bacteria;Acidobacteria;Acidobacteria_Gp2;Gp2',
 533: 'Bacteria;Acidobacteria;Acidobacteria_Gp2;Gp2',
 534: 'Bacteria;Acidobacteria;Acidobacteria_Gp2;Gp2',
 535: 'Bacteria;Acidobacteria;Acidobacteria_Gp3;Gp3',
 536: 'Bacteria;Acidobacteria;Acidobacteria_Gp3;Gp3',
 537: 'Bacteria;Acidobacteria;Acidobacteria_Gp3;Gp3',
 538: 'Bacteria;Acidobacteria;Acidobacteria_Gp3;Gp3',
 539: 'Bacteria;Acidobacteria;Acidobacteria_Gp4;Gp4',
 540: 'Bacteria;Acidobacteria;Acidobacteria_Gp4;Gp4',
 541: 'Bacteria;Acidobacteria;Acidobacteria_Gp6;Gp6',
 542: 'Bacteria;Actinobacteria;Actinobacteria',
 543: 'Bacteria;Actinobacteria;Actinobacteria',
 544: 'Bacteria;Actinobacteria;Actinobacteria',
 545: 'Bacteria;Actinobacteria;Actinobacteria',
 546: 'Bacteria;Actinobacteria;Actinobacteria',
 547: 'Bacteria;Actinobacteria;Actinobacteria',
 548: 'Bacteria;Actinobacteria;Actinobacteria',
 549: 'Bacteria;Actinobacteria;Actinobacteria',
 550: 'Bacteria;Actinobacteria;Actinobacteria',
 551: 'Bacteria;Actinobacteria;Actinobacteria;Acidimicrobiales',
 552: 'Bacteria;Actinobacteria;Actinobacteria;Acidimicrobiales;Iamiaceae;Iamia',
 553: 'Bacteria;Actinobacteria;Actinobacteria;Acidimicrobidae_incertae_sedis;Ilumatobacter',
 554: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 555: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 556: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 557: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 558: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 559: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 560: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 561: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 562: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 563: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 564: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 565: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 566: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 567: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 568: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 569: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 570: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 571: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 572: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 573: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 574: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 575: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 576: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 577: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 578: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 579: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 580: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 581: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 582: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 583: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 584: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 585: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 586: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 587: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 588: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 589: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 590: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 591: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 592: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 593: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 594: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 595: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 596: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 597: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 598: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 599: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 600: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 601: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 602: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 603: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 604: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 605: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 606: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 607: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 608: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 609: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 610: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 611: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 612: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 613: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 614: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 615: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 616: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 617: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 618: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 619: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 620: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 621: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 622: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 623: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 624: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 625: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 626: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 627: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 628: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 629: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 630: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 631: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 632: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 633: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 634: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 635: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 636: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 637: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 638: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 639: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 640: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 641: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 642: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 643: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 644: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 645: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 646: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 647: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 648: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 649: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 650: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 651: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 652: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 653: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 654: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 655: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 656: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 657: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 658: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 659: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 660: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 661: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 662: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 663: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 664: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 665: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 666: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 667: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 668: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 669: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 670: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 671: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 672: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 673: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 674: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 675: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 676: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 677: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 678: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 679: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 680: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 681: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 682: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 683: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 684: 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',

In [3]:
#meta_df.head()

meta_trim = meta_df[["AGE", "BBTYPE", "ETHNICITY", "GENDER", "LOCATION", "SAMPLEID"]]

meta = []
i = 0

for i in range(0, len(meta_df["AGE"])):
    age = meta_df["AGE"][i]
    bbtype = meta_df["BBTYPE"][i]
    ethnicity = meta_df["ETHNICITY"][i]
    gender = meta_df["GENDER"][i]
    location = meta_df["LOCATION"][i]
    sampleID = meta_df["SAMPLEID"][i]
    
    meta_dict = {"AGE": age, "BBTYPE": bbtype, "ETHNICITY": ethnicity, "GENDER": gender, "LOCATION": location, "SAMPLEID": str(sampleID)}
    
    meta.append(meta_dict)

meta

[{'AGE': 24.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'Beaufort/NC',
  'SAMPLEID': '940'},
 {'AGE': 34.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian/Midleastern',
  'GENDER': 'F',
  'LOCATION': 'Chicago/IL',
  'SAMPLEID': '941'},
 {'AGE': 49.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'Omaha/NE',
  'SAMPLEID': '943'},
 {'AGE': 44.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'European',
  'GENDER': 'M',
  'LOCATION': 'NewHaven/CT',
  'SAMPLEID': '944'},
 {'AGE': 48.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'Philidelphia/PA',
  'SAMPLEID': '945'},
 {'AGE': 42.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'Deerfield/MA',
  'SAMPLEID': '946'},
 {'AGE': 49.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'M',
  'LOCATION': 'ChapelHill/NC',
  'SAMPLEID': '947'},
 {'AGE': 20.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'M',
  'LOCATION': 'ChapelHill/NC',
  'SAMPLEID': '948'},
 {'AGE': 51.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'Durham/NC',
  'SAMPLEID': '949'},
 {'AGE': 51.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'M',
  'LOCATION': 'NewYork/NY',
  'SAMPLEID': '950'},
 {'AGE': 51.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'Seattle/WA',
  'SAMPLEID': '952'},
 {'AGE': 38.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'Chicago/IL',
  'SAMPLEID': '953'},
 {'AGE': 26.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'M',
  'LOCATION': 'NewYork/NY',
  'SAMPLEID': '954'},
 {'AGE': 27.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'NewYork/NY',
  'SAMPLEID': '955'},
 {'AGE': 16.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'M',
  'LOCATION': 'Jacksonville/NC',
  'SAMPLEID': '956'},
 {'AGE': 43.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'M',
  'LOCATION': 'Wilmington/NC',
  'SAMPLEID': '958'},
 {'AGE': 40.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'M',
  'LOCATION': 'Carrboro/NC',
  'SAMPLEID': '959'},
 {'AGE': 48.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'M',
  'LOCATION': 'Lexington/NC',
  'SAMPLEID': '960'},
 {'AGE': 35.0,
  'BBTYPE': 'i',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'Edmonton,AB',
  'SAMPLEID': '961'},
 {'AGE': 56.0,
  'BBTYPE': 'i',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'Washington,DC',
  'SAMPLEID': '962'},
 {'AGE': 33.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'Ithaca/NY',
  'SAMPLEID': '963'},
 {'AGE': 43.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'UK/London',
  'SAMPLEID': '964'},
 {'AGE': 56.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'M',
  'LOCATION': 'Needham/MA',
  'SAMPLEID': '966'},
 {'AGE': 43.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian/Jewish',
  'GENDER': 'F',
  'LOCATION': 'ChapelHill/NC',
  'SAMPLEID': '967'},
 {'AGE': 38.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'St.Louis/MI',
  'SAMPLEID': '968'},
 {'AGE': 31.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian/Asian',
  'GENDER': 'F',
  'LOCATION': 'ChevyChase/MD',
  'SAMPLEID': '969'},
 {'AGE': 42.0,
  'BBTYPE': 'i',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'SanDiego/CA',
  'SAMPLEID': '970'},
 {'AGE': 36.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Asian(South)',
  'GENDER': 'M',
  'LOCATION': 'SantaBarbara/CA',
  'SAMPLEID': '971'},
 {'AGE': 31.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'Charlotte/NC',
  'SAMPLEID': '972'},
 {'AGE': 4.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'Charlotte/NC',
  'SAMPLEID': '973'},
 {'AGE': 57.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'Raleigh/NC',
  'SAMPLEID': '974'},
 {'AGE': 60.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'NewCanaan/CT',
  'SAMPLEID': '975'},
 {'AGE': 21.0,
  'BBTYPE': nan,
  'ETHNICITY': 'Hispanic',
  'GENDER': 'F',
  'LOCATION': 'Durham/NC',
  'SAMPLEID': '978'},
 {'AGE': 34.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'M',
  'LOCATION': nan,
  'SAMPLEID': '1233'},
 {'AGE': nan,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': nan,
  'SAMPLEID': '1234'},
 {'AGE': 43.0,
  'BBTYPE': nan,
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': nan,
  'SAMPLEID': '1235'},
 {'AGE': 54.0,
  'BBTYPE': nan,
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': nan,
  'SAMPLEID': '1236'},
 {'AGE': 9.0,
  'BBTYPE': 'i',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'ChapelHill,NC',
  'SAMPLEID': '1237'},
 {'AGE': 41.0,
  'BBTYPE': 'i',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'Raleigh,NC',
  'SAMPLEID': '1238'},
 {'AGE': 44.0,
  'BBTYPE': 'i',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'Raleigh,NC',
  'SAMPLEID': '1242'},
 {'AGE': 49.0,
  'BBTYPE': 'i',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'M',
  'LOCATION': 'Raleigh,NC',
  'SAMPLEID': '1243'},
 {'AGE': 2.0,
  'BBTYPE': nan,
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'Atlanta,GA',
  'SAMPLEID': '1246'},
 {'AGE': 24.0,
  'BBTYPE': 'i',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'M',
  'LOCATION': 'Voss,NC',
  'SAMPLEID': '1253'},
 {'AGE': 1.0,
  'BBTYPE': 'o',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'Voss,NC',
  'SAMPLEID': '1254'},
 {'AGE': 31.0,
  'BBTYPE': 'i',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'f',
  'LOCATION': 'Smithfield,NC',
  'SAMPLEID': '1258'},
 {'AGE': 33.0,
  'BBTYPE': nan,
  'ETHNICITY': 'Caucasian',
  'GENDER': 'm',
  'LOCATION': 'Smithfield,NC',
  'SAMPLEID': '1259'},
 {'AGE': 10.0,
  'BBTYPE': nan,
  'ETHNICITY': 'Caucasian',
  'GENDER': 'm',
  'LOCATION': 'Smithfield,NC',
  'SAMPLEID': '1260'},
 {'AGE': 46.0,
  'BBTYPE': 'i',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'm',
  'LOCATION': 'Raleigh,NC',
  'SAMPLEID': '1264'},
 {'AGE': 10.0,
  'BBTYPE': 'i',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'f',
  'LOCATION': 'Raleigh,NC',
  'SAMPLEID': '1265'},
 {'AGE': 60.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'M',
  'LOCATION': nan,
  'SAMPLEID': '1273'},
 {'AGE': 18.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': nan,
  'SAMPLEID': '1275'},
 {'AGE': 34.0,
  'BBTYPE': 'O',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'M',
  'LOCATION': nan,
  'SAMPLEID': '1276'},
 {'AGE': 67.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': nan,
  'SAMPLEID': '1277'},
 {'AGE': 44.0,
  'BBTYPE': 'I',
  'ETHNICITY': nan,
  'GENDER': 'M',
  'LOCATION': nan,
  'SAMPLEID': '1278'},
 {'AGE': 60.0,
  'BBTYPE': 'O',
  'ETHNICITY': 'Black',
  'GENDER': 'F',
  'LOCATION': nan,
  'SAMPLEID': '1279'},
 {'AGE': 30.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'PacificIslander',
  'GENDER': 'F',
  'LOCATION': nan,
  'SAMPLEID': '1280'},
 {'AGE': 55.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': nan,
  'SAMPLEID': '1281'},
 {'AGE': 53.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': nan,
  'SAMPLEID': '1282'},
 {'AGE': 48.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'M',
  'LOCATION': nan,
  'SAMPLEID': '1283'},
 {'AGE': 30.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': nan,
  'SAMPLEID': '1284'},
 {'AGE': 42.0,
  'BBTYPE': 'Both',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'M',
  'LOCATION': nan,
  'SAMPLEID': '1285'},
 {'AGE': 38.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'M',
  'LOCATION': nan,
  'SAMPLEID': '1286'},
 {'AGE': 46.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'M',
  'LOCATION': nan,
  'SAMPLEID': '1287'},
 {'AGE': 52.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': nan,
  'SAMPLEID': '1288'},
 {'AGE': 38.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Black',
  'GENDER': 'F',
  'LOCATION': nan,
  'SAMPLEID': '1289'},
 {'AGE': 53.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': nan,
  'SAMPLEID': '1290'},
 {'AGE': 49.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': nan,
  'SAMPLEID': '1291'},
 {'AGE': 46.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'M',
  'LOCATION': nan,
  'SAMPLEID': '1292'},
 {'AGE': 68.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': nan,
  'SAMPLEID': '1293'},
 {'AGE': 46.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': nan,
  'SAMPLEID': '1294'},
 {'AGE': 48.0,
  'BBTYPE': 'Both',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': nan,
  'SAMPLEID': '1295'},
 {'AGE': 10.0,
  'BBTYPE': 'i',
  'ETHNICITY': 'Black',
  'GENDER': 'f',
  'LOCATION': 'Pinehurst,NC',
  'SAMPLEID': '1296'},
 {'AGE': 10.0,
  'BBTYPE': nan,
  'ETHNICITY': 'Caucasion',
  'GENDER': 'f',
  'LOCATION': 'Pinehurst,NC',
  'SAMPLEID': '1297'},
 {'AGE': 12.0,
  'BBTYPE': 'i',
  'ETHNICITY': 'White',
  'GENDER': 'm',
  'LOCATION': 'Pinehurst,NC',
  'SAMPLEID': '1298'},
 {'AGE': 40.0,
  'BBTYPE': nan,
  'ETHNICITY': 'Black',
  'GENDER': 'f',
  'LOCATION': 'Durham,NC',
  'SAMPLEID': '1308'},
 {'AGE': 6.0,
  'BBTYPE': nan,
  'ETHNICITY': 'Black',
  'GENDER': 'f',
  'LOCATION': 'Durham,NC',
  'SAMPLEID': '1309'},
 {'AGE': 3.0,
  'BBTYPE': nan,
  'ETHNICITY': 'Black',
  'GENDER': 'm',
  'LOCATION': 'Durham,NC',
  'SAMPLEID': '1310'},
 {'AGE': 55.0,
  'BBTYPE': 'o',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'Cary,NC',
  'SAMPLEID': '1374'},
 {'AGE': nan,
  'BBTYPE': 'Unknown',
  'ETHNICITY': nan,
  'GENDER': nan,
  'LOCATION': nan,
  'SAMPLEID': '1415'},
 {'AGE': nan,
  'BBTYPE': nan,
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'Sarasota,FL',
  'SAMPLEID': '1439'},
 {'AGE': 36.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'Raleigh,NC',
  'SAMPLEID': '1441'},
 {'AGE': 57.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'Raleigh,NC',
  'SAMPLEID': '1443'},
 {'AGE': 33.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'Shrewsbury,UK',
  'SAMPLEID': '1486'},
 {'AGE': 30.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'M',
  'LOCATION': 'Shrewsbury,UK',
  'SAMPLEID': '1487'},
 {'AGE': 28.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'WashingtonDC',
  'SAMPLEID': '1489'},
 {'AGE': 27.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'DurhamNC',
  'SAMPLEID': '1490'},
 {'AGE': 24.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'WashingtonDC',
  'SAMPLEID': '1491'},
 {'AGE': 35.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'M',
  'LOCATION': 'Boone,NC',
  'SAMPLEID': '1494'},
 {'AGE': 57.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'Raleigh,NC',
  'SAMPLEID': '1495'},
 {'AGE': 35.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'M',
  'LOCATION': 'Raleigh,NC',
  'SAMPLEID': '1497'},
 {'AGE': 33.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'M',
  'LOCATION': 'Waynesville,NC',
  'SAMPLEID': '1499'},
 {'AGE': 32.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'M',
  'LOCATION': 'Raleigh,NC',
  'SAMPLEID': '1500'},
 {'AGE': 38.0,
  'BBTYPE': 'I',
  'ETHNICITY': nan,
  'GENDER': 'M',
  'LOCATION': 'FallsChurch,VA',
  'SAMPLEID': '1501'},
 {'AGE': 27.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'Boone,NC',
  'SAMPLEID': '1502'},
 {'AGE': 32.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'Raleigh,NC',
  'SAMPLEID': '1503'},
 {'AGE': 27.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'Raleigh,NC',
  'SAMPLEID': '1504'},
 {'AGE': 26.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'Durham,NC',
  'SAMPLEID': '1505'},
 {'AGE': 21.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'Raleigh,NC',
  'SAMPLEID': '1506'},
 {'AGE': 46.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'NC',
  'SAMPLEID': '1507'},
 {'AGE': 60.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'M',
  'LOCATION': 'NC',
  'SAMPLEID': '1508'},
 {'AGE': 21.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Black',
  'GENDER': 'F',
  'LOCATION': 'NC',
  'SAMPLEID': '1510'},
 {'AGE': 46.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'NC',
  'SAMPLEID': '1511'},
 {'AGE': 55.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'M',
  'LOCATION': 'NC',
  'SAMPLEID': '1512'},
 {'AGE': 15.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'M',
  'LOCATION': 'NC',
  'SAMPLEID': '1513'},
 {'AGE': 3.0,
  'BBTYPE': 'o',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'NC',
  'SAMPLEID': '1514'},
 {'AGE': 51.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'NC',
  'SAMPLEID': '1515'},
 {'AGE': 57.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'M',
  'LOCATION': 'NC',
  'SAMPLEID': '1516'},
 {'AGE': 27.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'M',
  'LOCATION': 'NC',
  'SAMPLEID': '1517'},
 {'AGE': 25.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'GA',
  'SAMPLEID': '1518'},
 {'AGE': 25.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'NC',
  'SAMPLEID': '1519'},
 {'AGE': 10.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'NC',
  'SAMPLEID': '1521'},
 {'AGE': 14.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'M',
  'LOCATION': 'NC',
  'SAMPLEID': '1524'},
 {'AGE': 6.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'M',
  'LOCATION': 'NC',
  'SAMPLEID': '1526'},
 {'AGE': 34.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'NC',
  'SAMPLEID': '1527'},
 {'AGE': 54.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'NC',
  'SAMPLEID': '1530'},
 {'AGE': 39.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'M',
  'LOCATION': 'NC',
  'SAMPLEID': '1531'},
 {'AGE': 38.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'NC',
  'SAMPLEID': '1532'},
 {'AGE': 37.0,
  'BBTYPE': 'o',
  'ETHNICITY': 'Black',
  'GENDER': 'M',
  'LOCATION': 'NC',
  'SAMPLEID': '1533'},
 {'AGE': 42.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'NC',
  'SAMPLEID': '1534'},
 {'AGE': 35.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'M',
  'LOCATION': 'NC',
  'SAMPLEID': '1535'},
 {'AGE': 26.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'NC',
  'SAMPLEID': '1536'},
 {'AGE': 28.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'M',
  'LOCATION': 'NC',
  'SAMPLEID': '1537'},
 {'AGE': 39.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'NC',
  'SAMPLEID': '1539'},
 {'AGE': 30.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'M',
  'LOCATION': 'NC',
  'SAMPLEID': '1540'},
 {'AGE': 26.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'NC',
  'SAMPLEID': '1541'},
 {'AGE': 36.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'M',
  'LOCATION': 'NC',
  'SAMPLEID': '1542'},
 {'AGE': 34.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'NC',
  'SAMPLEID': '1543'},
 {'AGE': 33.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'NC',
  'SAMPLEID': '1544'},
 {'AGE': 39.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'NC',
  'SAMPLEID': '1545'},
 {'AGE': 34.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'M',
  'LOCATION': 'NC',
  'SAMPLEID': '1546'},
 {'AGE': 38.0,
  'BBTYPE': 'I',
  'ETHNICITY': nan,
  'GENDER': 'M',
  'LOCATION': 'NC',
  'SAMPLEID': '1547'},
 {'AGE': 6.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'M',
  'LOCATION': 'NC',
  'SAMPLEID': '1548'},
 {'AGE': 37.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'NC',
  'SAMPLEID': '1549'},
 {'AGE': 29.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'NC',
  'SAMPLEID': '1550'},
 {'AGE': 26.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'M',
  'LOCATION': 'NC',
  'SAMPLEID': '1551'},
 {'AGE': 25.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'M',
  'LOCATION': 'NC',
  'SAMPLEID': '1552'},
 {'AGE': 50.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'NC',
  'SAMPLEID': '1553'},
 {'AGE': 18.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'NC',
  'SAMPLEID': '1554'},
 {'AGE': 26.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'M',
  'LOCATION': 'NC',
  'SAMPLEID': '1555'},
 {'AGE': 34.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Hispanic',
  'GENDER': 'M',
  'LOCATION': 'NC',
  'SAMPLEID': '1556'},
 {'AGE': 26.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'NC',
  'SAMPLEID': '1557'},
 {'AGE': 26.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'M',
  'LOCATION': 'NC',
  'SAMPLEID': '1558'},
 {'AGE': 31.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'M',
  'LOCATION': 'NC',
  'SAMPLEID': '1561'},
 {'AGE': 39.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'M',
  'LOCATION': 'MT',
  'SAMPLEID': '1562'},
 {'AGE': 31.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'MT',
  'SAMPLEID': '1563'},
 {'AGE': 36.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'NC',
  'SAMPLEID': '1564'},
 {'AGE': 33.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'NC',
  'SAMPLEID': '1572'},
 {'AGE': 53.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'M',
  'LOCATION': 'NC',
  'SAMPLEID': '1573'},
 {'AGE': 30.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'M',
  'LOCATION': 'OK',
  'SAMPLEID': '1574'},
 {'AGE': 33.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'NC',
  'SAMPLEID': '1576'},
 {'AGE': 26.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'M',
  'LOCATION': 'NC',
  'SAMPLEID': '1577'},
 {'AGE': 22.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Asian(American)',
  'GENDER': 'F',
  'LOCATION': 'NC',
  'SAMPLEID': '1581'},
 {'AGE': 22.0,
  'BBTYPE': 'I',
  'ETHNICITY': 'Caucasian',
  'GENDER': 'F',
  'LOCATION': 'NC',
  'SAMPLEID': '1601'}]

In [3]:
#sample_df.head()
names = list(sample_df)
sample_names = []

for name in names:
    sample_names.append(name)

sample_names.remove("otu_id")
sample_names

['BB_940',
 'BB_941',
 'BB_943',
 'BB_944',
 'BB_945',
 'BB_946',
 'BB_947',
 'BB_948',
 'BB_949',
 'BB_950',
 'BB_952',
 'BB_953',
 'BB_954',
 'BB_955',
 'BB_956',
 'BB_958',
 'BB_959',
 'BB_960',
 'BB_961',
 'BB_962',
 'BB_963',
 'BB_964',
 'BB_966',
 'BB_967',
 'BB_968',
 'BB_969',
 'BB_970',
 'BB_971',
 'BB_972',
 'BB_973',
 'BB_974',
 'BB_975',
 'BB_978',
 'BB_1233',
 'BB_1234',
 'BB_1235',
 'BB_1236',
 'BB_1237',
 'BB_1238',
 'BB_1242',
 'BB_1243',
 'BB_1246',
 'BB_1253',
 'BB_1254',
 'BB_1258',
 'BB_1259',
 'BB_1260',
 'BB_1264',
 'BB_1265',
 'BB_1273',
 'BB_1275',
 'BB_1276',
 'BB_1277',
 'BB_1278',
 'BB_1279',
 'BB_1280',
 'BB_1281',
 'BB_1282',
 'BB_1283',
 'BB_1284',
 'BB_1285',
 'BB_1286',
 'BB_1287',
 'BB_1288',
 'BB_1289',
 'BB_1290',
 'BB_1291',
 'BB_1292',
 'BB_1293',
 'BB_1294',
 'BB_1295',
 'BB_1296',
 'BB_1297',
 'BB_1298',
 'BB_1308',
 'BB_1309',
 'BB_1310',
 'BB_1374',
 'BB_1415',
 'BB_1439',
 'BB_1441',
 'BB_1443',
 'BB_1486',
 'BB_1487',
 'BB_1489',
 'BB_1490',
 'BB_1491',
 'BB_1494',
 'BB_1495',
 'BB_1497',
 'BB_1499',
 'BB_1500',
 'BB_1501',
 'BB_1502',
 'BB_1503',
 'BB_1504',
 'BB_1505',
 'BB_1506',
 'BB_1507',
 'BB_1508',
 'BB_1510',
 'BB_1511',
 'BB_1512',
 'BB_1513',
 'BB_1514',
 'BB_1515',
 'BB_1516',
 'BB_1517',
 'BB_1518',
 'BB_1519',
 'BB_1521',
 'BB_1524',
 'BB_1526',
 'BB_1527',
 'BB_1530',
 'BB_1531',
 'BB_1532',
 'BB_1533',
 'BB_1534',
 'BB_1535',
 'BB_1536',
 'BB_1537',
 'BB_1539',
 'BB_1540',
 'BB_1541',
 'BB_1542',
 'BB_1543',
 'BB_1544',
 'BB_1545',
 'BB_1546',
 'BB_1547',
 'BB_1548',
 'BB_1549',
 'BB_1550',
 'BB_1551',
 'BB_1552',
 'BB_1553',
 'BB_1554',
 'BB_1555',
 'BB_1556',
 'BB_1557',
 'BB_1558',
 'BB_1561',
 'BB_1562',
 'BB_1563',
 'BB_1564',
 'BB_1572',
 'BB_1573',
 'BB_1574',
 'BB_1576',
 'BB_1577',
 'BB_1581',
 'BB_1601']

In [5]:
column_df.head()

      COLUMN     TYPE           DESCRIPTION
0   SAMPLEID  INTEGER             sample_id
1      EVENT     TEXT     Collection event
2  ETHNICITY     TEXT             Ethnicity
3     GENDER     TEXT  Gender (male/female)
4        AGE  INTEGER        Age (in years)

In [6]:
sample_df.head()

,otu_id,BB_940,BB_941,BB_943,BB_944,BB_945,BB_946,BB_947,BB_948,BB_949,...,BB_1562,BB_1563,BB_1564,BB_1572,BB_1573,BB_1574,BB_1576,BB_1577,BB_1581,BB_1601
0,1,0.0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,0.0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,0.0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0.0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,0.0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0

In [7]:
otu_df.head()

   otu_id                        lowest_taxonomic_unit_found
0       1  Archaea;Euryarchaeota;Halobacteria;Halobacteri...
1       2  Archaea;Euryarchaeota;Halobacteria;Halobacteri...
2       3  Archaea;Euryarchaeota;Halobacteria;Halobacteri...
3       4  Archaea;Euryarchaeota;Methanobacteria;Methanob...
4       5  Archaea;Euryarchaeota;Methanobacteria;Methanob...

In [8]:
meta_df.head(15)

,SAMPLEID,EVENT,ETHNICITY,GENDER,AGE,WFREQ,BBTYPE,LOCATION,COUNTRY012,ZIP012,...,DOG,CAT,IMPSURFACE013,NPP013,MMAXTEMP013,PFC013,IMPSURFACE1319,NPP1319,MMAXTEMP1319,PFC1319
0,940,BellyButtonsScienceOnline,Caucasian,F,24.0,2.0,I,Beaufort/NC,usa,22306,...,no,no,8852.0,37.172222,54.5,NaN,1,NaN,33.990002,25.5
1,941,NaN,Caucasian/Midleastern,F,34.0,1.0,I,Chicago/IL,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,943,BellyButtonsScienceOnline,Caucasian,F,49.0,1.0,I,Omaha/NE,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,944,BellyButtonsScienceOnline,European,M,44.0,1.0,I,NewHaven/CT,usa,7079,...,no,yes,NaN,35.816666,16.0,NaN,0,6567.0,32.403332,28.5
4,945,BellyButtonsScienceOnline,Caucasian,F,48.0,1.0,I,Philidelphia/PA,usa,84404,...,no,no,NaN,37.783333,4.0,NaN,0,5613.0,33.634445,24.0
5,946,BellyButtonsScienceOnline,Caucasian,F,42.0,3.0,I,Deerfield/MA,usa,12538,...,no,yes,NaN,34.761112,15.5,NaN,0,6273.0,29.403334,67.5
6,947,BellyButtonsScienceOnline,Caucasian,M,49.0,6.0,I,ChapelHill/NC,usa,48823,...,no,yes,7491.0,30.356667,31.0,NaN,0,5357.0,30.881111,16.5
7,948,BellyButtonsScienceOnline,Caucasian,M,20.0,NaN,I,ChapelHill/NC,usa,27613,...,no,no,NaN,53.887779,0.0,NaN,31,NaN,31.730000,22.5
8,949,BellyButtonsScienceOnline,Caucasian,F,51.0,3.0,I,Durham/NC,usa,7009,...,no,no,NaN,35.534443,36.0,NaN,5,NaN,35.534443,36.0
9,950,BellyButtonsScienceOnline,Caucasian,M,51.0,5.0,I,NewYork/NY,usa,1730,...,yes,no,6273.0,29.403334,67.5,NaN,0,NaN,30.481112,33.0
10,952,BellyButtonsScienceOnline,Caucasian,F,51.0,7.0,I,Seattle/WA,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,953,BellyButtonsScienceOnline,Caucasian,F,38.0,2.0,I,Chicago/IL,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,954,BellyButtonsScienceOnline,Caucasian,M,26.0,7.0,I,NewYork/NY,usa,45429,...,NaN,NaN,6919.0,34.007778,34.5,NaN,21,6074.0,34.263332,14.5
13,955,BellyButtonsScienceOnline,Caucasian,F,27.0,7.0,I,NewYork/NY,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,956,BellyButtonsScienceOnline,Caucasian,M,16.0,7.0,I,Jacksonville/NC,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
wash_dict = {}
j = 0
for j in range(0, len(meta_df["SAMPLEID"])):
    s_id = "BB_" + str(meta_df["SAMPLEID"][j])
    w_freq = meta_df["WFREQ"][j]
    
    wash_dict[s_id] = w_freq
    
wash_dict

{'BB_1233': 0.0,
 'BB_1234': nan,
 'BB_1235': 0.0,
 'BB_1236': 6.0,
 'BB_1237': 2.0,
 'BB_1238': 0.0,
 'BB_1242': 1.0,
 'BB_1243': nan,
 'BB_1246': 7.0,
 'BB_1253': 5.0,
 'BB_1254': 5.0,
 'BB_1258': 7.0,
 'BB_1259': 7.0,
 'BB_1260': 7.0,
 'BB_1264': 0.0,
 'BB_1265': 0.0,
 'BB_1273': 3.0,
 'BB_1275': 0.0,
 'BB_1276': 0.0,
 'BB_1277': 7.0,
 'BB_1278': 7.0,
 'BB_1279': 9.0,
 'BB_1280': nan,
 'BB_1281': 3.0,
 'BB_1282': nan,
 'BB_1283': 7.0,
 'BB_1284': 7.0,
 'BB_1285': nan,
 'BB_1286': 7.0,
 'BB_1287': nan,
 'BB_1288': 7.0,
 'BB_1289': nan,
 'BB_1290': 5.0,
 'BB_1291': 0.0,
 'BB_1292': nan,
 'BB_1293': 1.0,
 'BB_1294': nan,
 'BB_1295': 7.0,
 'BB_1296': 4.0,
 'BB_1297': 5.0,
 'BB_1298': 3.0,
 'BB_1308': 7.0,
 'BB_1309': 5.0,
 'BB_1310': 5.0,
 'BB_1374': 7.0,
 'BB_1415': nan,
 'BB_1439': nan,
 'BB_1441': 4.0,
 'BB_1443': 3.0,
 'BB_1486': 0.0,
 'BB_1487': 0.0,
 'BB_1489': 0.0,
 'BB_1490': 0.0,
 'BB_1491': 3.0,
 'BB_1494': 0.0,
 'BB_1495': 3.0,
 'BB_1497': 0.0,
 'BB_1499': 0.0,
 'BB_1500': 0.0,
 'BB_1501': 0.0,
 'BB_1502': 0.0,
 'BB_1503': 7.0,
 'BB_1504': 0.0,
 'BB_1505': 0.0,
 'BB_1506': 0.0,
 'BB_1507': 0.0,
 'BB_1508': 0.0,
 'BB_1510': 1.0,
 'BB_1511': 0.0,
 'BB_1512': 7.0,
 'BB_1513': 0.0,
 'BB_1514': 7.0,
 'BB_1515': 1.0,
 'BB_1516': 0.0,
 'BB_1517': 0.0,
 'BB_1518': 0.0,
 'BB_1519': 0.0,
 'BB_1521': 0.0,
 'BB_1524': 4.0,
 'BB_1526': 7.0,
 'BB_1527': 7.0,
 'BB_1530': 1.0,
 'BB_1531': 2.0,
 'BB_1532': 0.0,
 'BB_1533': 0.0,
 'BB_1534': 0.0,
 'BB_1535': 7.0,
 'BB_1536': 7.0,
 'BB_1537': 0.0,
 'BB_1539': 7.0,
 'BB_1540': 0.0,
 'BB_1541': 0.0,
 'BB_1542': nan,
 'BB_1543': 3.0,
 'BB_1544': 1.0,
 'BB_1545': 7.0,
 'BB_1546': 3.0,
 'BB_1547': 0.0,
 'BB_1548': 0.0,
 'BB_1549': 3.0,
 'BB_1550': 7.0,
 'BB_1551': 0.0,
 'BB_1552': 3.0,
 'BB_1553': 0.0,
 'BB_1554': 0.0,
 'BB_1555': 0.0,
 'BB_1556': 0.0,
 'BB_1557': 2.0,
 'BB_1558': 1.0,
 'BB_1561': 2.0,
 'BB_1562': 0.0,
 'BB_1563': 0.0,
 'BB_1564': 5.0,
 'BB_1572': 0.0,
 'BB_1573': 0.0,
 'BB_1574': 7.0,
 'BB_1576': 0.0,
 'BB_1577': 0.0,
 'BB_1581': 2.0,
 'BB_1601': 2.0,
 'BB_940': 2.0,
 'BB_941': 1.0,
 'BB_943': 1.0,
 'BB_944': 1.0,
 'BB_945': 1.0,
 'BB_946': 3.0,
 'BB_947': 6.0,
 'BB_948': nan,
 'BB_949': 3.0,
 'BB_950': 5.0,
 'BB_952': 7.0,
 'BB_953': 2.0,
 'BB_954': 7.0,
 'BB_955': 7.0,
 'BB_956': 7.0,
 'BB_958': 5.0,
 'BB_959': 5.0,
 'BB_960': 7.0,
 'BB_961': 4.0,
 'BB_962': 1.0,
 'BB_963': 3.5,
 'BB_964': 7.0,
 'BB_966': 0.0,
 'BB_967': 1.0,
 'BB_968': 6.0,
 'BB_969': 7.0,
 'BB_970': 0.0,
 'BB_971': 1.0,
 'BB_972': 7.0,
 'BB_973': 1.0,
 'BB_974': nan,
 'BB_975': 3.0,
 'BB_978': nan}

In [5]:
sample_list = []

for item in sample_names:
    col = sample_df.sort_values(item, ascending=False)
    o_id= col["otu_id"].tolist()
    s_val=col[item].tolist()
    
    s_dict = {"otu_ids": o_id, "sample_values": s_val}
    sample_list.append(s_dict)

In [28]:
sample_list

[{'otu_ids': 1166    1167
  2858    2859
  481      482
  2263    2264
  40        41
  1188    1189
  351      352
  188      189
  2317    2318
  1976    1977
  3449    3450
  873      874
  1958    1959
  2190    2191
  1949    1950
  2076    2077
  2274    2275
  2183    2184
  943      944
  2243    2244
  2418    2419
  2023    2024
  2810    2811
  2781    2782
  164      165
  2395    2396
  2246    2247
  2010    2011
  829      830
  1794    1795
          ...
  1314    1315
  1289    1290
  1288    1289
  1287    1288
  1286    1287
  1262    1263
  1263    1264
  1264    1265
  1265    1266
  1266    1267
  1267    1268
  1268    1269
  1269    1270
  1270    1271
  1271    1272
  1272    1273
  1274    1275
  1275    1276
  1276    1277
  1277    1278
  1278    1279
  1279    1280
  1280    1281
  1281    1282
  1282    1283
  1283    1284
  1284    1285
  1285    1286
  3673    3674
  3461    3462
  Name: otu_id, Length: 3674, dtype: int64, 'sample_values': 1166    163.0
  2858    126.0
  481     113.0
  2263     78.0
  40       71.0
  1188     51.0
  351      50.0
  188      47.0
  2317     40.0
  1976     40.0
  3449     37.0
  873      36.0
  1958     30.0
  2190     28.0
  1949     25.0
  2076     23.0
  2274     22.0
  2183     19.0
  943      19.0
  2243     14.0
  2418     13.0
  2023     13.0
  2810     13.0
  2781     12.0
  164      12.0
  2395     11.0
  2246     11.0
  2010     11.0
  829      10.0
  1794     10.0
          ...
  1314      0.0
  1289      0.0
  1288      0.0
  1287      0.0
  1286      0.0
  1262      0.0
  1263      0.0
  1264      0.0
  1265      0.0
  1266      0.0
  1267      0.0
  1268      0.0
  1269      0.0
  1270      0.0
  1271      0.0
  1272      0.0
  1274      0.0
  1275      0.0
  1276      0.0
  1277      0.0
  1278      0.0
  1279      0.0
  1280      0.0
  1281      0.0
  1282      0.0
  1283      0.0
  1284      0.0
  1285      0.0
  3673      0.0
  3461      NaN
  Name: BB_940, Length: 3674, dtype: float64}, {'otu_ids': 2721    2722
  943      944
  2418    2419
  2538    2539
  3449    3450
  1794    1795
  2388    2389
  1313    1314
  921      922
  1166    1167
  2858    2859
  962      963
  2963    2964
  2307    2308
  2650    2651
  481      482
  873      874
  1869    1870
  2907    2908
  2263    2264
  40        41
  727      728
  1187    1188
  1958    1959
  1925    1926
  351      352
  2781    2782
  295      296
  3311    3312
  1309    1310
          ...
  1280    1281
  1256    1257
  1254    1255
  1228    1229
  1240    1241
  1229    1230
  1230    1231
  1231    1232
  1232    1233
  1233    1234
  1234    1235
  1235    1236
  1236    1237
  1237    1238
  1238    1239
  1239    1240
  1241    1242
  1253    1254
  1242    1243
  1243    1244
  1244    1245
  1245    1246
  1246    1247
  1247    1248
  1248    1249
  1249    1250
  1250    1251
  1251    1252
  1252    1253
  3673    3674
  Name: otu_id, Length: 3674, dtype: int64, 'sample_values': 2721    194
  943     178
  2418    162
  2538     92
  3449     84
  1794     40
  2388     37
  1313     28
  921      27
  1166     24
  2858     21
  962      21
  2963     13
  2307     10
  2650     10
  481       8
  873       8
  1869      5
  2907      5
  2263      4
  40        4
  727       3
  1187      3
  1958      3
  1925      3
  351       3
  2781      3
  295       2
  3311      2
  1309      2
         ...
  1280      0
  1256      0
  1254      0
  1228      0
  1240      0
  1229      0
  1230      0
  1231      0
  1232      0
  1233      0
  1234      0
  1235      0
  1236      0
  1237      0
  1238      0
  1239      0
  1241      0
  1253      0
  1242      0
  1243      0
  1244      0
  1245      0
  1246      0
  1247      0
  1248      0
  1249      0
  1250      0
  1251      0
  1252      0
  3673      0
  Name: BB_941, Length: 3674, dtype: int64}, {'otu_ids': 1794    1795
  3311    3312
  921      922
  2464    2465
  2463    2464
  2442    2443
  2443    2444
  2444    2445
  2445    2446
  2446    2447
  2447    2448
  2448    2449
  2449    2450
  2450    2451
  2465    2466
  2451    2452
  2452    2453
  2453    2454
  2440    2441
  2454    2455
  2455    2456
  2456    2457
  2457    2458
  2458    2459
  2459    2460
  2460    2461
  2461    2462
  2462    2463
  2441    2442
  2439    2440
          ...
  1260    1261
  1235    1236
  1234    1235
  1233    1234
  1219    1220
  1208    1209
  1209    1210
  1210    1211
  1211    1212
  1212    1213
  1213    1214
  1214    1215
  1215    1216
  1216    1217
  1217    1218
  1218    1219
  1220    1221
  1232    1233
  1221    1222
  1222    1223
  1223    1224
  1224    1225
  1225    1226
  1226    1227
  1227    1228
  1228    1229
  1229    1230
  1230    1231
  1231    1232
  3673    3674
  Name: otu_id, Length: 3674, dtype: int64, 'sample_values': 1794    2
  3311    1
  921     1
  2464    0
  2463    0
  2442    0
  2443    0
  2444    0
  2445    0
  2446    0
  2447    0
  2448    0
  2449    0
  2450    0
  2465    0
  2451    0
  2452    0
  2453    0
  2440    0
  2454    0
  2455    0
  2456    0
  2457    0
  2458    0
  2459    0
  2460    0
  2461    0
  2462    0
  2441    0
  2439    0
         ..
  1260    0
  1235    0
  1234    0
  1233    0
  1219    0
  1208    0
  1209    0
  1210    0
  1211    0
  1212    0
  1213    0
  1214    0
  1215    0
  1216    0
  1217    0
  1218    0
  1220    0
  1232    0
  1221    0
  1222    0
  1223    0
  1224    0
  1225    0
  1226    0
  1227    0
  1228    0
  1229    0
  1230    0
  1231    0
  3673    0
  Name: BB_943, Length: 3674, dtype: int64}, {'otu_ids': 921      922
  3554    3555
  942      943
  1012    1013
  1794    1795
  943      944
  3367    3368
  922      923
  1769    1770
  3515    3516
  3119    3120
  2307    2308
  3540    3541
  3311    3312
  40        41
  2650    2651
  3526    3527
  1928    1929
  2936    2937
  969      970
  3523    3524
  3522    3523
  2721    2722
  3520    3521
  727      728
  2129    2130
  3439    3440
  1034    1035
  680      681
  3281    3282
          ...
  1279    1280
  1255    1256
  1253    1254
  1227    1228
  1239    1240
  1228    1229
  1229    1230
  1230    1231
  1231    1232
  1232    1233
  1233    1234
  1234    1235
  1235    1236
  1236    1237
  1237    1238
  1238    1239
  1240    1241
  1252    1253
  1241    1242
  1242    1243
  1243    1244
  1244    1245
  1245    1246
  1246    1247
  1247    1248
  1248    1249
  1249    1250
  1250    1251
  1251    1252
  3673    3674
  Name: otu_id, Length: 3674, dtype: int64, 'sample_values': 921     278
  3554     33
  942      19
  1012     18
  1794     11
  943       8
  3367      7
  922       5
  1769      5
  3515      5
  3119      4
  2307      4
  3540      4
  3311      3
  40        3
  2650      3
  3526      3
  1928      3
  2936      2
  969       2
  3523      2
  3522      2
  2721      2
  3520      2
  727       2
  2129      2
  3439      2
  1034      2
  680       1
  3281      1
         ...
  1279      0
  1255      0
  1253      0
  1227      0
  1239      0
  1228      0
  1229      0
  1230      0
  1231      0
  1232      0
  1233      0
  1234      0
  1235      0
  1236      0
  1237      0
  1238      0
  1240      0
  1252      0
  1241      0
  1242      0
  1243      0
  1244      0
  1245      0
  1246      0
  1247      0
  1248      0
  1249      0
  1250      0
  1251      0
  3673      0
  Name: BB_944, Length: 3674, dtype: int64}, {'otu_ids': 943      944
  1794    1795
  921      922
  2418    2419
  2858    2859
  942      943
  2721    2722
  1166    1167
  2650    2651
  1313    1314
  718      719
  2963    2964
  2189    2190
  1168    1169
  295      296
  40        41
  2781    2782
  2010    2011
  727      728
  2538    2539
  481      482
  2460    2461
  3119    3120
  1285    1286
  2570    2571
  1199    1200
  605      606
  2317    2318
  908      909
  2388    2389
          ...
  1281    1282
  1257    1258
  1255    1256
  1229    1230
  1241    1242
  1230    1231
  1231    1232
  1232    1233
  1233    1234
  1234    1235
  1235    1236
  1236    1237
  1237    1238
  1238    1239
  1239    1240
  1240    1241
  1242    1243
  1254    1255
  1243    1244
  1244    1245
  1245    1246
  1246    1247
  1247    1248
  1248    1249
  1249    1250
  1250    1251
  1251    1252
  1252    1253
  1253    1254
  3673    3674
  Name: otu_id, Length: 3674, dtype: int64, 'sample_values': 943     274
  1794    141
  921     129
  2418    110
  2858     40
  942      37
  2721     35
  1166     32
  2650     26
  1313     20
  718      17
  2963     15
  2189     15
  1168     15
  295      15
  40       14
  2781     14
  2010     12
  727      10
  2538     10
  481       9
  2460      8
  3119      8
  1285      8
  2570      8
  1199      7
  605       7
  2317      7
  908       7
  2388      6
         ...
  1281      0
  1257      0
  1255      0
  1229      0
  1241      0
  1230      0
  1231      0
  1232      0
  1233      0
  1234      0
  1235      0
  1236      0
  1237      0
  1238      0
  1239      0
  1240      0
  1242      0
  1254      0
  1243      0
  1244      0
  1245      0
  1246      0
  1247      0
  1248      0
  1249      0
  1250      0
  1251      0
  1252      0
  1253      0
  3673      0
  Name: BB_945, Length: 3674, dtype: int64}, {'otu_ids': 1166    1167
  2858    2859
  2010    2011
  40        41
  295      296
  2781    2782
  908      909
  2721    2722
  2963    2964
  1313    1314
  1168    1169
  1285    1286
  2189    2190
  3458    3459
  2570    2571
  2418    2419
  2907    2908
  1199    1200
  2317    2318
  829      830
  481      482
  1188    1189
  3449    3450
  2984    2985
  2274    2275
  2538    2539
  2190    2191
  2395    2396
  2482    2483
  390      391
          ...
  1319    1320
  1321    1322
  1295    1296
  1294    1295
  1293    1294
  1292    1293
  1263    1264
  1264    1265
  1265    1266
  1266    1267
  1267    1268
  1269    1270
  1270    1271
  1271    1272
  1272    1273
  1273    1274
  1275    1276
  1276    1277
  1277    1278
  1278    1279
  1279    1280
  1280    1281
  1281    1282
  1282    1283
  1283    1284
  1284    1285
  1286    1287
  1289    1290
  1290    1291
  3673    3674
  Name: otu_id, Length: 3674, dtype: int64, 'sample_values': 1166    217
  2858    195
  2010    159
  40      153
  295     123
  2781    116
  908     116
  2721    114
  2963    109
  1313    100
  1168     93
  1285     83
  2189     80
  3458     42
  2570     39
  2418     36
  2907     34
  1199     33
  2317     31
  829      28
  481      28
  1188     26
  3449     24
  2984     20
  2274     19
  2538     18
  2190     17
  2395     16
  2482     13
  390      12
         ...
  1319      0
  1321      0
  1295      0
  1294      0
  1293      0
  1292      0
  1263      0
  1264      0
  1265      0
  1266      0
  1267      0
  1269      0
  1270      0
  1271      0
  1272      0
  1273      0
  1275      0
  1276      0
  1277      0
  1278      0
  1279      0
  1280      0
  1281      0
  1282      0
  1283      0
  1284      0
  1286      0
  1289      0
  1290      0
  3673      0
  Name: BB_946, Length: 3674, dtype: int64}, {'otu_ids': 2418    2419
  2721    2722
  2858    2859
  943      944
  2650    2651
  1794    1795
  3449    3450
  921      922
  1166    1167
  2963    2964
  2538    2539
  727      728
  2010    2011
  40        41
  1313    1314
  1168    1169
  2388    2389
  2189    2190
  295      296
  908      909
  1285    1286
  2317    2318
  2531    2532
  2907    2908
  1452    1453
  2570    2571
  2671    2672
  3458    3459
  2556    2557
  2398    2399
          ...
  1276    1277
  1252    1253
  1250    1251
  1222    1223
  1236    1237
  1223    1224
  1224    1225
  1225    1226
  1226    1227
  1227    1228
  1228    1229
  1229    1230
  1230    1231
  1233    1234
  1234    1235
  1235    1236
  1237    1238
  1249    1250
  1238    1239
  1239    1240
  1240    1241
  1241    1242
  1242    1243
  1243    1244
  1244    1245
  1245    1246
  1246    1247
  1247    1248
  1248    1249
  3673    3674
  Name: otu_id, Length: 3674, dtype: int64, 'sample_values': 2418    412
  2721    236
  2858    200
  943     135
  2650    115
  1794    102
  3449     46
  921      45
  1166     27
  2963     24
  2538     23
  727      19
  2010     15
  40       13
  1313     11
  1168     10
  2388      9
  2189      9
  295       9
  908       7
  1285      6
  2317      6
  2531      5
  2907      5
  1452      5
  2570      5
  2671      4
  3458      4
  2556      4
  2398      4
         ...
  1276      0
  1252      0
  1250      0
  1222      0
  1236      0
  1223      0
  1224      0
  1225      0
  1226      0
  1227      0
  1228      0
  1229      0
  1230      0
  1233      0
  1234      0
  1235      0
  1237      0
  1249      0
  1238      0
  1239      0
  1240      0
  1241      0
  1242      0
  1243      0
  1244      0
  1245      0
  1246      0
  1247      0
  1248      0
  3673      0
  Name: BB_947, Length: 3674, dtype: int64}, {'otu_ids': 727      728
  921      922
  2721    2722
  942      943
  2418    2419
  481      482
  2858    2859
  1976    1977
  882      883
  3642    3643
  1188    1189
  2010    2011
  1166    1167
  2781    2782
  2263    2264
  829      830
  3035    3036
  3449    3450
  2395    2396
  2183    2184
  1313    1314
  40        41
  943      944
  2984    2985
  2538    2539
  2307    2308
  1794    1795
  981      982
  2907    2908
  1168    1169
          ...
  1283    1284
  1281    1282
  1254    1255
  1266    1267
  1255    1256
  1256    1257
  1257    1258
  1258    1259
  1259    1260
  1260    1261
  1261    1262
  1262    1263
  1263    1264
  1264    1265
  1265    1266
  1267    1268
  1280    1281
  1268    1269
  1269    1270
  1270    1271
  1272    1273
  1273    1274
  1274    1275
  1275    1276
  1276    1277
  1277    1278
  1278    1279
  1279    1280
  3673    3674
  3420    3421
  Name: otu_id, Length: 3674, dtype: int64, 'sample_values': 727     225.0
  921     185.0
  2721     64.0
  942      57.0
  2418     55.0
  481      50.0
  2858     47.0
  1976     29.0
  882      23.0
  3642     20.0
  1188     20.0
  2010     19.0
  1166     18.0
  2781     18.0
  2263     18.0
  829      15.0
  3035     14.0
  3449     13.0
  2395     12.0
  2183     12.0
  1313     10.0
  40       10.0
  943       9.0
  2984      9.0
  2538      9.0
  2307      8.0
  1794      8.0
  981       7.0
  2907      7.0
  1168      7.0
          ...
  1283      0.0
  1281      0.0
  1254      0.0
  1266      0.0
  1255      0.0
  1256      0.0
  1257      0.0
  1258      0.0
  1259      0.0
  1260      0.0
  1261      0.0
  1262      0.0
  1263      0.0
  1264      0.0
  1265      0.0
  1267      0.0
  1280      0.0
  1268      0.0
  1269      0.0
  1270      0.0
  1272      0.0
  1273      0.0
  1274      0.0
  1275      0.0
  1276      0.0
  1277      0.0
  1278      0.0
  1279      0.0
  3673      0.0
  3420      NaN
  Name: BB_948, Length: 3674, dtype: float64}, {'otu_ids': 2418    2419
  943      944
  1794    1795
  921      922
  962      963
  2444    2445
  2445    2446
  2446    2447
  2447    2448
  2448    2449
  2449    2450
  2450    2451
  2451    2452
  2452    2453
  2453    2454
  2454    2455
  2455    2456
  2442    2443
  2456    2457
  2457    2458
  2458    2459
  2459    2460
  2460    2461
  2461    2462
  2462    2463
  2463    2464
  2464    2465
  2465    2466
  2466    2467
  2467    2468
          ...
  1261    1262
  1236    1237
  1235    1236
  1234    1235
  1220    1221
  1209    1210
  1210    1211
  1211    1212
  1212    1213
  1213    1214
  1214    1215
  1215    1216
  1216    1217
  1217    1218
  1218    1219
  1219    1220
  1221    1222
  1233    1234
  1222    1223
  1223    1224
  1224    1225
  1225    1226
  1226    1227
  1227    1228
  1228    1229
  1229    1230
  1230    1231
  1231    1232
  1232    1233
  3673    3674
  Name: otu_id, Length: 3674, dtype: int64, 'sample_values': 2418    8
  943     4
  1794    3
  921     1
  962     1
  2444    0
  2445    0
  2446    0
  2447    0
  2448    0
  2449    0
  2450    0
  2451    0
  2452    0
  2453    0
  2454    0
  2455    0
  2442    0
  2456    0
  2457    0
  2458    0
  2459    0
  2460    0
  2461    0
  2462    0
  2463    0
  2464    0
  2465    0
  2466    0
  2467    0
         ..
  1261    0
  1236    0
  1235    0
  1234    0
  1220    0
  1209    0
  1210    0
  1211    0
  1212    0
  1213    0
  1214    0
  1215    0
  1216    0
  1217    0
  1218    0
  1219    0
  1221    0
  1233    0
  1222    0
  1223    0
  1224    0
  1225    0
  1226    0
  1227    0
  1228    0
  1229    0
  1230    0
  1231    0
  1232    0
  3673    0
  Name: BB_949, Length: 3674, dtype: int64}, {'otu_ids': 1794    1795
  921      922
  943      944
  3359    3360
  1928    1929
  829      830
  1723    1724
  1727    1728
  1769    1770
  3540    3541
  3035    3036
  3401    3402
  3580    3581
  2418    2419
  3397    3398
  594      595
  3195    3196
  3526    3527
  3522    3523
  1452    1453
  1681    1682
  2858    2859
  3395    3396
  1299    1300
  3355    3356
  3183    3184
  3042    3043
  1705    1706
  1599    1600
  3122    3123
          ...
  1236    1237
  1234    1235
  1208    1209
  1220    1221
  1209    1210
  1210    1211
  1211    1212
  1212    1213
  1213    1214
  1214    1215
  1215    1216
  1216    1217
  1217    1218
  1218    1219
  1219    1220
  1221    1222
  1233    1234
  1222    1223
  1223    1224
  1224    1225
  1225    1226
  1226    1227
  1227    1228
  1228    1229
  1229    1230
  1230    1231
  1231    1232
  1232    1233
  3673    3674
  3425    3426
  Name: otu_id, Length: 3674, dtype: int64, 'sample_values': 1794    427.0
  921     123.0
  943      14.0
  3359     13.0
  1928     13.0
  829      11.0
  1723     10.0
  1727      7.0
  1769      7.0
  3540      7.0
  3035      6.0
  3401      5.0
  3580      5.0
  2418      5.0
  3397      4.0
  594       4.0
  3195      4.0
  3526      4.0
  3522      4.0
  1452      4.0
  1681      4.0
  2858      4.0
  3395      4.0
  1299      3.0
  3355      3.0
  3183      3.0
  3042      3.0
  1705      3.0
  1599      3.0
  3122      2.0
          ...
  1236      0.0
  1234      0.0
  1208      0.0
  1220      0.0
  1209      0.0
  1210      0.0
  1211      0.0
  1212      0.0
  1213      0.0
  1214      0.0
  1215      0.0
  1216      0.0
  1217      0.0
  1218      0.0
  1219      0.0
  1221      0.0
  1233      0.0
  1222      0.0
  1223      0.0
  1224      0.0
  1225      0.0
  1226      0.0
  1227      0.0
  1228      0.0
  1229      0.0
  1230      0.0
  1231      0.0
  1232      0.0
  3673      0.0
  3425      NaN
  Name: BB_950, Length: 3674, dtype: float64}, {'otu_ids': 921      922
  942      943
  2538    2539
  727      728
  981      982
  988      989
  882      883
  2721    2722
  2418    2419
  938      939
  718      719
  2460    2461
  817      818
  605      606
  2388    2389
  1869    1870
  943      944
  2010    2011
  2858    2859
  916      917
  829      830
  2183    2184
  2166    2167
  481      482
  2263    2264
  2307    2308
  2265    2266
  788      789
  736      737
  2753    2754
          ...
  1286    1287
  1262    1263
  1260    1261
  1234    1235
  1246    1247
  1235    1236
  1236    1237
  1237    1238
  1238    1239
  1239    1240
  1240    1241
  1241    1242
  1242    1243
  1243    1244
  1244    1245
  1245    1246
  1247    1248
  1259    1260
  1248    1249
  1249    1250
  1250    1251
  1251    1252
  1252    1253
  1253    1254
  1254    1255
  1255    1256
  1256    1257
  1257    1258
  1258    1259
  3673    3674
  Name: otu_id, Length: 3674, dtype: int64, 'sample_values': 921     182
  942      79
  2538     52
  727      43
  981      38

In [30]:
col.head()

,otu_id,BB_940,BB_941,BB_943,BB_944,BB_945,BB_946,BB_947,BB_948,BB_949,...,BB_1562,BB_1563,BB_1564,BB_1572,BB_1573,BB_1574,BB_1576,BB_1577,BB_1581,BB_1601
1928,1929,0.0,2,0,3,4,0,0,1.0,0,...,0,1,6,0,1,0,121,6,4,166
3029,3030,0.0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,1,0,0,129
1794,1795,10.0,40,2,11,141,2,102,8.0,3,...,143,1,537,26,3,14,1,130,176,97
893,894,0.0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,94
1166,1167,163.0,24,0,0,32,217,27,18.0,0,...,0,0,0,93,0,14,0,0,0,73

In [34]:
sample_list[152]

{'otu_ids': 1928    1929
 3029    3030
 1794    1795
 893      894
 1166    1167
 1925    1926
 3041    3042
 1929    1930
 943      944
 2418    2419
 1923    1924
 3394    3395
 1848    1849
 3028    3029
 1916    1917
 1926    1927
 3449    3450
 1924    1925
 921      922
 2650    2651
 2538    2539
 1292    1293
 908      909
 1869    1870
 843      844
 1920    1921
 3011    3012
 2388    2389
 2265    2266
 2721    2722
         ...
 1270    1271
 1244    1245
 1242    1243
 1214    1215
 1227    1228
 1215    1216
 1216    1217
 1218    1219
 1219    1220
 1220    1221
 1221    1222
 1222    1223
 1223    1224
 1224    1225
 1225    1226
 1226    1227
 1228    1229
 1241    1242
 1229    1230
 1230    1231
 1232    1233
 1233    1234
 1234    1235
 1235    1236
 1236    1237
 1237    1238
 1238    1239
 1239    1240
 1240    1241
 3673    3674
 Name: otu_id, Length: 3674, dtype: int64, 'sample_values': 1928    166
 3029    129
 1794     97
 893      94
 1166     73
 1925     51
 3041     32
 1929     32
 943      25
 2418     22
 1923     16
 3394     15
 1848     15
 3028     14
 1916     13
 1926     13
 3449     12
 1924     11
 921      10
 2650     10
 2538      9
 1292      9
 908       9
 1869      9
 843       7
 1920      7
 3011      6
 2388      6
 2265      6
 2721      5
        ...
 1270      0
 1244      0
 1242      0
 1214      0
 1227      0
 1215      0
 1216      0
 1218      0
 1219      0
 1220      0
 1221      0
 1222      0
 1223      0
 1224      0
 1225      0
 1226      0
 1228      0
 1241      0
 1229      0
 1230      0
 1232      0
 1233      0
 1234      0
 1235      0
 1236      0
 1237      0
 1238      0
 1239      0
 1240      0
 3673      0
 Name: BB_1601, Length: 3674, dtype: int64}

In [6]:
i = 0
sample = "BB_940"
for name in sample_names:
    if name == sample:
        sample_meta = meta[i]
        print(sample_meta)
    else:
        i+= 1

{'AGE': 24.0, 'BBTYPE': 'I', 'ETHNICITY': 'Caucasian', 'GENDER': 'F', 'LOCATION': 'Beaufort/NC', 'SAMPLEID': '940'}

In [7]:
from flask import Flask, jsonify, render_template

In [12]:
sample_meta

{'AGE': 24.0,
 'BBTYPE': 'I',
 'ETHNICITY': 'Caucasian',
 'GENDER': 'F',
 'LOCATION': 'Beaufort/NC',
 'SAMPLEID': '940'}

In [10]:
j = 0
sample = "BB_940"
for name in sample_names:
        print(name)
        print(sample)
        if name == str(sample):
            sample_dict = sample_list[j]
            print(sample_dict)
            print(j)
            break
        else:
            j+=1

BB_940
BB_940

In [12]:
type([0,1,2])

list

In [9]:
sample_dict

{'otu_ids': [1167,
  2859,
  482,
  2264,
  41,
  1189,
  352,
  189,
  2318,
  1977,
  3450,
  874,
  1959,
  2191,
  1950,
  2077,
  2275,
  2184,
  944,
  2244,
  2419,
  2024,
  2811,
  2782,
  165,
  2396,
  2247,
  2011,
  830,
  1795,
  2964,
  2722,
  2178,
  307,
  2908,
  1193,
  1208,
  2039,
  2167,
  1274,
  2739,
  2737,
  2936,
  1962,
  2335,
  833,
  1314,
  2186,
  907,
  2546,
  121,
  357,
  1169,
  2110,
  725,
  2571,
  1232,
  340,
  259,
  1960,
  258,
  342,
  1968,
  2188,
  170,
  2491,
  1505,
  2291,
  1497,
  412,
  1503,
  2475,
  2235,
  159,
  513,
  2065,
  2342,
  2350,
  2483,
  1498,
  198,
  244,
  2949,
  2062,
  3427,
  1174,
  2054,
  2136,
  1179,
  185,
  1115,
  2051,
  791,
  3439,
  794,
  1155,
  246,
  235,
  3453,
  2917,
  2096,
  1191,
  2915,
  2093,
  226,
  821,
  1159,
  2114,
  2115,
  2084,
  2080,
  2068,
  841,
  2603,
  2752,
  2968,
  2268,
  386,
  2229,
  1254,
  400,
  2508,
  404,
  407,
  414,
  1524,
  2256,
  1515,
  2263,
  1502,
  381,
  1501,
  1496,
  1495,
  2473,
  1484,
  650,
  2750,
  620,
  2334,
  2423,
  2413,
  593,
  1243,
  2217,
  300,
  2633,
  1199,
  2165,
  314,
  320,
  2985,
  2549,
  2989,
  327,
  328,
  1600,
  2994,
  2542,
  1217,
  2216,
  2192,
  2539,
  2197,
  728,
  1223,
  1576,
  2202,
  359,
  361,
  1227,
  2212,
  373,
  854,
  564,
  881,
  133,
  19,
  1954,
  79,
  1984,
  81,
  154,
  2829,
  84,
  2758,
  1965,
  1935,
  1094,
  2820,
  2852,
  11,
  93,
  102,
  922,
  42,
  39,
  2795,
  919,
  866,
  2036,
  22,
  2837,
  2876,
  2040,
  1944,
  2840,
  24,
  122,
  2873,
  2753,
  1991,
  1947,
  1997,
  2728,
  2723,
  2471,
  2721,
  2472,
  2479,
  2488,
  2734,
  2733,
  2487,
  2486,
  2480,
  2474,
  2481,
  2732,
  2727,
  2485,
  2724,
  2731,
  2478,
  2484,
  2477,
  2489,
  2725,
  2729,
  2482,
  2476,
  2726,
  2730,
  2636,
  2490,
  2511,
  2505,
  2711,
  2506,
  2507,
  2509,
  2710,
  2510,
  2709,
  2512,
  2712,
  2513,
  2514,
  2515,
  2708,
  2516,
  2517,
  2518,
  2707,
  2504,
  2713,
  2720,
  2717,
  2719,
  2492,
  2493,
  2718,
  2469,
  2494,
  2495,
  2496,
  2497,
  2503,
  2498,
  2499,
  2500,
  2716,
  2501,
  2715,
  2714,
  2502,
  2470,
  2463,
  2468,
  2417,
  2410,
  2411,
  2412,
  2749,
  2748,
  2414,
  2747,
  2415,
  2416,
  2418,
  2408,
  2746,
  2420,
  2421,
  2422,
  2745,
  2424,
  2425,
  2426,
  2427,
  2409,
  2407,
  2467,
  2394,
  2385,
  2386,
  2387,
  2388,
  2389,
  2390,
  2391,
  2392,
  2393,
  2395,
  2406,
  2397,
  2398,
  2399,
  2400,
  2401,
  2402,
  2403,
  2404,
  2405,
  2744,
  2743,
  2428,
  2458,
  2450,
  2451,
  2738,
  2452,
  2453,
  2454,
  2455,
  2456,
  2457,
  2459,
  2429,
  2460,
  2461,
  2462,
  2706,
  2464,
  2465,
  2736,
  2466,
  2735,
  2449,
  2448,
  2447,
  2446,
  2430,
  2431,
  2432,
  2433,
  2434,
  2435,
  2436,
  2437,
  2438,
  2742,
  2439,
  2440,
  2741,
  2740,
  2441,
  2442,
  2443,
  2444,
  2445,
  2519,
  2529,
  2520,
  2604,
  2659,
  2658,
  2592,
  2657,
  2656,
  2655,
  2593,
  2594,
  2595,
  2596,
  2597,
  2598,
  2599,
  2600,
  2654,
  2601,
  2602,
  2653,
  2652,
  2591,
  2590,
  2660,
  2666,
  2580,
  2581,
  2669,
  2582,
  2668,
  2667,
  2583,
  2584,
  2665,
  2661,
  2585,
  2586,
  2664,
  2587,
  2663,
  2662,
  2588,
  2589,
  2651,
  2650,
  2521,
  2605,
  2621,
  2642,
  2622,
  2623,
  2624,
  2625,
  2626,
  2627,
  2628,
  2641,
  2629,
  2630,
  2640,
  2631,
  2639,
  2632,
  2638,
  2637,
  2634,
  2643,
  2620,
  2619,
  2612,
  2649,
  2606,
  2607,
  2608,
  2609,
  2648,
  2610,
  2611,
  2647,
  2618,
  2646,
  2613,
  2645,
  2614,
  2644,
  2615,
  2616,
  2617,
  2579,
  2578,
  2670,
  2577,
  2697,
  2696,
  2536,
  2695,
  2694,
  2693,
  2537,
  2538,
  2540,
  2692,
  2541,
  2691,
  2690,
  2689,
  2688,
  2543,
  2687,
  2544,
  2545,
  2698,
  2699,
  2535,
  2527,
  2705,
  2522,
  2523,
  2524,
  2525,
  2704,
  2526,
  2703,
  2528,
  2700,
  2702,
  2635,
  2530,
  2531,
  2532,
  2533,
  2701,
  2534,
  2547,
  2686,
  2685,
  2568,
  2675,
  2563,
  2674,
  2564,
  2673,
  2565,
  2566,
  2567,
  2569,
  2562,
  2570,
  2672,
  2572,
  2573,
  2671,
  2574,
  2575,
  2384,
  2676,
  2561,
  2684,
  2553,
  2683,
  2548,
  2682,
  2681,
  2680,
  2550,
  2551,
  2552,
  2554,
  2560,
  2679,
  2555,
  2556,
  2557,
  2678,
  2677,
  2558,
  2559,
  2576,
  1,
  2383,
  2044,
  2046,
  2047,
  2048,
  2049,
  2050,
  2052,
  2053,
  2055,
  2056,
  2057,
  2058,
  2059,
  2060,
  2061,
  2063,
  2064,
  2066,
  2067,
  2069,
  2070,
  2071,
  2072,
  2073,
  2045,
  2043,
  2075,
  2042,
  2015,
  2016,
  2017,
  2018,
  2019,
  2020,
  2021,
  2022,
  2023,
  2025,
  2026,
  2027,
  2028,
  2029,
  2030,
  2031,
  2032,
  2033,
  2034,
  2035,
  2037,
  2038,
  2041,
  2074,
  2076,
  2013,
  2108,
  2111,
  2112,
  2113,
  2116,
  2117,
  2118,
  2119,
  2120,
  2121,
  2122,
  2123,
  2124,
  2125,
  2126,
  2127,
  2128,
  2129,
  2130,
  2131,
  2132,
  2133,
  2134,
  2135,
  2109,
  2107,
  2078,
  2106,
  2079,
  2081,
  2082,
  2083,
  2085,
  2086,
  2087,
  2088,
  2089,
  2090,
  2091,
  2092,
  2094,
  2095,
  2097,
  2098,
  2099,
  2100,
  2101,
  2102,
  2103,
  2104,
  2105,
  2014,
  2012,
  2138,
  1917,
  1919,
  1920,
  1921,
  1922,
  1923,
  1924,
  1925,
  1926,
  1927,
  1928,
  1929,
  1930,
  1931,
  1932,
  1933,
  1934,
  1936,
  1937,
  1938,
  1939,
  1940,
  1941,
  1942,
  1918,
  1916,
  1945,
  1915,
  1892,
  1893,
  1894,
  1895,
  1896,
  1897,
  1898,
  1899,
  1900,
  1901,
  1902,
  1903,
  1904,
  1905,
  1906,
  1907,
  1908,
  1909,
  1910,
  1911,
  1912,
  1913,
  1914,
  1943,
  1946,
  2010,
  1982,
  1985,
  1986,
  1987,
  1988,
  1989,
  1990,
  1992,
  1993,
  1994,
  1995,
  1996,
  1998,
  1999,
  2000,
  2001,
  2002,
  2003,
  2004,
  2005,
  2006,
  2007,
  2008,
  2009,
  1983,
  1981,
  1948,
  1980,
  1949,
  1951,
  1952,
  1953,
  1955,
  1956,
  1957,
  1958,
  1961,
  1963,
  1964,
  1966,
  1967,
  1969,
  1970,
  1971,
  1972,
  1973,
  1974,
  1975,
  1976,
  1978,
  1979,
  2137,
  2139,
  2382,
  2297,
  2299,
  2300,
  2301,
  2302,
  2303,
  2304,
  2305,
  2306,
  2307,
  2308,
  2309,
  2310,
  2311,
  2312,
  2313,
  2314,
  2315,
  2316,
  2317,
  2320,
  2321,
  2322,
  2323,
  2298,
  2296,
  2325,
  2295,
  2270,
  2271,
  2272,
  2273,
  2274,
  2276,
  2277,
  2278,
  2279,
  2280,
  2281,
  2282,
  2283,
  2284,
  2285,
  2286,
  2287,
  2288,
  2289,
  2290,
  2292,
  2293,
  2294,
  2324,
  2326,
  2267,
  2357,
  2359,
  2360,
  2361,
  2362,
  2363,
  2364,
  2365,
  2366,
  2367,
  2368,
  2369,
  2370,
  2371,
  2372,
  2373,
  2374,
  2375,
  2376,
  2377,
  2378,
  2379,
  2380,
  2381,
  2358,
  2356,
  2327,
  2355,
  2328,
  2329,
  2330,
  2331,
  2332,
  2333,
  2336,
  2337,
  2338,
  2339,
  2340,
  2341,
  2343,
  2344,
  2345,
  2346,
  2347,
  2348,
  2349,
  2351,
  2352,
  2353,
  2354,
  2269,
  2266,
  2140,
  2168,
  2170,
  2171,
  2172,
  2173,
  2174,
  2175,
  2176,
  2177,
  2179,
  2180,
  2181,
  2182,
  2183,
  2185,
  2187,
  2189,
  2190,
  2193,
  2194,
  2195,
  2196,
  2198,
  2199,
  2169,
  2166,
  2201,
  2164,
  2141,
  2142,
  2143,
  2144,
  2145,
  2146,
  2147,
  2148,
  2149,
  2150,
  2151,
  2152,
  2153,
  2154,
  2155,
  2156,
  2157,
  2158,
  2159,
  2160,
  2161,
  2162,
  2163,
  2200,
  2203,
  2265,
  2234,
  2237,
  2238,
  2239,
  2240,
  2241,
  2242,
  2243,
  2245,
  2246,
  2248,
  2249,
  2250,
  2251,
  2252,
  2253,
  2254,
  2255,
  2257,
  2258,
  2259,
  2260,
  2261,
  2262,
  2236,
  2233,
  2204,
  2232,
  2205,
  2206,
  2207,
  2208,
  2209,
  2210,
  2211,
  2213,
  2214,
  2215,
  2218,
  2219,
  2220,
  2221,
  2222,
  2223,
  2224,
  2225,
  2226,
  2227,
  2228,
  2230,
  2231,
  2319,
  2800,
  2751,
  3376,
  3365,
  3366,
  3367,
  3368,
  ...],
 'sample_values': [163.0,
  126.0,
  113.0,
  78.0,
  71.0,
  51.0,
  50.0,
  47.0,
  40.0,
  40.0,
  37.0,
  36.0,
  30.0,
  28.0,
  25.0,
  23.0,
  22.0,
  19.0,
  19.0,
  14.0,
  13.0,
  13.0,
  13.0,
  12.0,
  12.0,
  11.0,
  11.0,
  11.0,
  10.0,
  10.0,
  10.0,
  8.0,
  7.0,
  7.0,
  7.0,
  6.0,
  5.0,
  5.0,
  5.0,
  4.0,
  4.0,
  4.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  ...]}

In [8]:
sample_list[0]

{'otu_ids': [1167,
  2859,
  482,
  2264,
  41,
  1189,
  352,
  189,
  2318,
  1977,
  3450,
  874,
  1959,
  2191,
  1950,
  2077,
  2275,
  2184,
  944,
  2244,
  2419,
  2024,
  2811,
  2782,
  165,
  2396,
  2247,
  2011,
  830,
  1795,
  2964,
  2722,
  2178,
  307,
  2908,
  1193,
  1208,
  2039,
  2167,
  1274,
  2739,
  2737,
  2936,
  1962,
  2335,
  833,
  1314,
  2186,
  907,
  2546,
  121,
  357,
  1169,
  2110,
  725,
  2571,
  1232,
  340,
  259,
  1960,
  258,
  342,
  1968,
  2188,
  170,
  2491,
  1505,
  2291,
  1497,
  412,
  1503,
  2475,
  2235,
  159,
  513,
  2065,
  2342,
  2350,
  2483,
  1498,
  198,
  244,
  2949,
  2062,
  3427,
  1174,
  2054,
  2136,
  1179,
  185,
  1115,
  2051,
  791,
  3439,
  794,
  1155,
  246,
  235,
  3453,
  2917,
  2096,
  1191,
  2915,
  2093,
  226,
  821,
  1159,
  2114,
  2115,
  2084,
  2080,
  2068,
  841,
  2603,
  2752,
  2968,
  2268,
  386,
  2229,
  1254,
  400,
  2508,
  404,
  407,
  414,
  1524,
  2256,
  1515,
  2263,
  1502,
  381,
  1501,
  1496,
  1495,
  2473,
  1484,
  650,
  2750,
  620,
  2334,
  2423,
  2413,
  593,
  1243,
  2217,
  300,
  2633,
  1199,
  2165,
  314,
  320,
  2985,
  2549,
  2989,
  327,
  328,
  1600,
  2994,
  2542,
  1217,
  2216,
  2192,
  2539,
  2197,
  728,
  1223,
  1576,
  2202,
  359,
  361,
  1227,
  2212,
  373,
  854,
  564,
  881,
  133,
  19,
  1954,
  79,
  1984,
  81,
  154,
  2829,
  84,
  2758,
  1965,
  1935,
  1094,
  2820,
  2852,
  11,
  93,
  102,
  922,
  42,
  39,
  2795,
  919,
  866,
  2036,
  22,
  2837,
  2876,
  2040,
  1944,
  2840,
  24,
  122,
  2873,
  2753,
  1991,
  1947,
  1997,
  2728,
  2723,
  2471,
  2721,
  2472,
  2479,
  2488,
  2734,
  2733,
  2487,
  2486,
  2480,
  2474,
  2481,
  2732,
  2727,
  2485,
  2724,
  2731,
  2478,
  2484,
  2477,
  2489,
  2725,
  2729,
  2482,
  2476,
  2726,
  2730,
  2636,
  2490,
  2511,
  2505,
  2711,
  2506,
  2507,
  2509,
  2710,
  2510,
  2709,
  2512,
  2712,
  2513,
  2514,
  2515,
  2708,
  2516,
  2517,
  2518,
  2707,
  2504,
  2713,
  2720,
  2717,
  2719,
  2492,
  2493,
  2718,
  2469,
  2494,
  2495,
  2496,
  2497,
  2503,
  2498,
  2499,
  2500,
  2716,
  2501,
  2715,
  2714,
  2502,
  2470,
  2463,
  2468,
  2417,
  2410,
  2411,
  2412,
  2749,
  2748,
  2414,
  2747,
  2415,
  2416,
  2418,
  2408,
  2746,
  2420,
  2421,
  2422,
  2745,
  2424,
  2425,
  2426,
  2427,
  2409,
  2407,
  2467,
  2394,
  2385,
  2386,
  2387,
  2388,
  2389,
  2390,
  2391,
  2392,
  2393,
  2395,
  2406,
  2397,
  2398,
  2399,
  2400,
  2401,
  2402,
  2403,
  2404,
  2405,
  2744,
  2743,
  2428,
  2458,
  2450,
  2451,
  2738,
  2452,
  2453,
  2454,
  2455,
  2456,
  2457,
  2459,
  2429,
  2460,
  2461,
  2462,
  2706,
  2464,
  2465,
  2736,
  2466,
  2735,
  2449,
  2448,
  2447,
  2446,
  2430,
  2431,
  2432,
  2433,
  2434,
  2435,
  2436,
  2437,
  2438,
  2742,
  2439,
  2440,
  2741,
  2740,
  2441,
  2442,
  2443,
  2444,
  2445,
  2519,
  2529,
  2520,
  2604,
  2659,
  2658,
  2592,
  2657,
  2656,
  2655,
  2593,
  2594,
  2595,
  2596,
  2597,
  2598,
  2599,
  2600,
  2654,
  2601,
  2602,
  2653,
  2652,
  2591,
  2590,
  2660,
  2666,
  2580,
  2581,
  2669,
  2582,
  2668,
  2667,
  2583,
  2584,
  2665,
  2661,
  2585,
  2586,
  2664,
  2587,
  2663,
  2662,
  2588,
  2589,
  2651,
  2650,
  2521,
  2605,
  2621,
  2642,
  2622,
  2623,
  2624,
  2625,
  2626,
  2627,
  2628,
  2641,
  2629,
  2630,
  2640,
  2631,
  2639,
  2632,
  2638,
  2637,
  2634,
  2643,
  2620,
  2619,
  2612,
  2649,
  2606,
  2607,
  2608,
  2609,
  2648,
  2610,
  2611,
  2647,
  2618,
  2646,
  2613,
  2645,
  2614,
  2644,
  2615,
  2616,
  2617,
  2579,
  2578,
  2670,
  2577,
  2697,
  2696,
  2536,
  2695,
  2694,
  2693,
  2537,
  2538,
  2540,
  2692,
  2541,
  2691,
  2690,
  2689,
  2688,
  2543,
  2687,
  2544,
  2545,
  2698,
  2699,
  2535,
  2527,
  2705,
  2522,
  2523,
  2524,
  2525,
  2704,
  2526,
  2703,
  2528,
  2700,
  2702,
  2635,
  2530,
  2531,
  2532,
  2533,
  2701,
  2534,
  2547,
  2686,
  2685,
  2568,
  2675,
  2563,
  2674,
  2564,
  2673,
  2565,
  2566,
  2567,
  2569,
  2562,
  2570,
  2672,
  2572,
  2573,
  2671,
  2574,
  2575,
  2384,
  2676,
  2561,
  2684,
  2553,
  2683,
  2548,
  2682,
  2681,
  2680,
  2550,
  2551,
  2552,
  2554,
  2560,
  2679,
  2555,
  2556,
  2557,
  2678,
  2677,
  2558,
  2559,
  2576,
  1,
  2383,
  2044,
  2046,
  2047,
  2048,
  2049,
  2050,
  2052,
  2053,
  2055,
  2056,
  2057,
  2058,
  2059,
  2060,
  2061,
  2063,
  2064,
  2066,
  2067,
  2069,
  2070,
  2071,
  2072,
  2073,
  2045,
  2043,
  2075,
  2042,
  2015,
  2016,
  2017,
  2018,
  2019,
  2020,
  2021,
  2022,
  2023,
  2025,
  2026,
  2027,
  2028,
  2029,
  2030,
  2031,
  2032,
  2033,
  2034,
  2035,
  2037,
  2038,
  2041,
  2074,
  2076,
  2013,
  2108,
  2111,
  2112,
  2113,
  2116,
  2117,
  2118,
  2119,
  2120,
  2121,
  2122,
  2123,
  2124,
  2125,
  2126,
  2127,
  2128,
  2129,
  2130,
  2131,
  2132,
  2133,
  2134,
  2135,
  2109,
  2107,
  2078,
  2106,
  2079,
  2081,
  2082,
  2083,
  2085,
  2086,
  2087,
  2088,
  2089,
  2090,
  2091,
  2092,
  2094,
  2095,
  2097,
  2098,
  2099,
  2100,
  2101,
  2102,
  2103,
  2104,
  2105,
  2014,
  2012,
  2138,
  1917,
  1919,
  1920,
  1921,
  1922,
  1923,
  1924,
  1925,
  1926,
  1927,
  1928,
  1929,
  1930,
  1931,
  1932,
  1933,
  1934,
  1936,
  1937,
  1938,
  1939,
  1940,
  1941,
  1942,
  1918,
  1916,
  1945,
  1915,
  1892,
  1893,
  1894,
  1895,
  1896,
  1897,
  1898,
  1899,
  1900,
  1901,
  1902,
  1903,
  1904,
  1905,
  1906,
  1907,
  1908,
  1909,
  1910,
  1911,
  1912,
  1913,
  1914,
  1943,
  1946,
  2010,
  1982,
  1985,
  1986,
  1987,
  1988,
  1989,
  1990,
  1992,
  1993,
  1994,
  1995,
  1996,
  1998,
  1999,
  2000,
  2001,
  2002,
  2003,
  2004,
  2005,
  2006,
  2007,
  2008,
  2009,
  1983,
  1981,
  1948,
  1980,
  1949,
  1951,
  1952,
  1953,
  1955,
  1956,
  1957,
  1958,
  1961,
  1963,
  1964,
  1966,
  1967,
  1969,
  1970,
  1971,
  1972,
  1973,
  1974,
  1975,
  1976,
  1978,
  1979,
  2137,
  2139,
  2382,
  2297,
  2299,
  2300,
  2301,
  2302,
  2303,
  2304,
  2305,
  2306,
  2307,
  2308,
  2309,
  2310,
  2311,
  2312,
  2313,
  2314,
  2315,
  2316,
  2317,
  2320,
  2321,
  2322,
  2323,
  2298,
  2296,
  2325,
  2295,
  2270,
  2271,
  2272,
  2273,
  2274,
  2276,
  2277,
  2278,
  2279,
  2280,
  2281,
  2282,
  2283,
  2284,
  2285,
  2286,
  2287,
  2288,
  2289,
  2290,
  2292,
  2293,
  2294,
  2324,
  2326,
  2267,
  2357,
  2359,
  2360,
  2361,
  2362,
  2363,
  2364,
  2365,
  2366,
  2367,
  2368,
  2369,
  2370,
  2371,
  2372,
  2373,
  2374,
  2375,
  2376,
  2377,
  2378,
  2379,
  2380,
  2381,
  2358,
  2356,
  2327,
  2355,
  2328,
  2329,
  2330,
  2331,
  2332,
  2333,
  2336,
  2337,
  2338,
  2339,
  2340,
  2341,
  2343,
  2344,
  2345,
  2346,
  2347,
  2348,
  2349,
  2351,
  2352,
  2353,
  2354,
  2269,
  2266,
  2140,
  2168,
  2170,
  2171,
  2172,
  2173,
  2174,
  2175,
  2176,
  2177,
  2179,
  2180,
  2181,
  2182,
  2183,
  2185,
  2187,
  2189,
  2190,
  2193,
  2194,
  2195,
  2196,
  2198,
  2199,
  2169,
  2166,
  2201,
  2164,
  2141,
  2142,
  2143,
  2144,
  2145,
  2146,
  2147,
  2148,
  2149,
  2150,
  2151,
  2152,
  2153,
  2154,
  2155,
  2156,
  2157,
  2158,
  2159,
  2160,
  2161,
  2162,
  2163,
  2200,
  2203,
  2265,
  2234,
  2237,
  2238,
  2239,
  2240,
  2241,
  2242,
  2243,
  2245,
  2246,
  2248,
  2249,
  2250,
  2251,
  2252,
  2253,
  2254,
  2255,
  2257,
  2258,
  2259,
  2260,
  2261,
  2262,
  2236,
  2233,
  2204,
  2232,
  2205,
  2206,
  2207,
  2208,
  2209,
  2210,
  2211,
  2213,
  2214,
  2215,
  2218,
  2219,
  2220,
  2221,
  2222,
  2223,
  2224,
  2225,
  2226,
  2227,
  2228,
  2230,
  2231,
  2319,
  2800,
  2751,
  3376,
  3365,
  3366,
  3367,
  3368,
  ...],
 'sample_values': [163.0,
  126.0,
  113.0,
  78.0,
  71.0,
  51.0,
  50.0,
  47.0,
  40.0,
  40.0,
  37.0,
  36.0,
  30.0,
  28.0,
  25.0,
  23.0,
  22.0,
  19.0,
  19.0,
  14.0,
  13.0,
  13.0,
  13.0,
  12.0,
  12.0,
  11.0,
  11.0,
  11.0,
  10.0,
  10.0,
  10.0,
  8.0,
  7.0,
  7.0,
  7.0,
  6.0,
  5.0,
  5.0,
  5.0,
  4.0,
  4.0,
  4.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  3.0,
  2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  ...]}